### ISSUE TITLE
Does not update information with Laravel Nova

### ISSUE THREAD

**Issue by freewhite4** [Astrotomic/laravel-translatable#106]
not update:
![image](https://user-images.githubusercontent.com/21085186/68948632-59860e00-07c9-11ea-9078-8bc2ce3fa356.png)

update:
![image](https://user-images.githubusercontent.com/21085186/68950402-26457e00-07cd-11ea-80d5-ffbd1623fe81.png)

**Comment by romanzipp** [comment]
Did you find a solution @freewhite4 ?

**Comment by Gummibeer** [comment]
I'm sorry but I don't have a nova license and haven't worked with it.
So I can't provide any information.
