### ISSUE TITLE
How can we acquire this for pivot table values?

### ISSUE THREAD

**Issue by arjunksankar** [Astrotomic/laravel-translatable#107]
We need to add translation for a pivot table value. Can this be done

**Comment by Lloople** [comment]
Since your pivot table contains more fields than just the related keys, you could create a model for that table and modify the current relations. I've used this approach many times in the past :👍

**Comment by arjunksankar** [comment]
Thank you so much for your support.

**Comment by Gummibeer** [comment]
#19
