### ISSUE TITLE
Possible to get a translation and copy it with another locale?

### ISSUE THREAD

**Issue by notflip** [Astrotomic/laravel-translatable#110]
I'm wondering what the best way is to go about this?

**Comment by Lloople** [comment]
This question is not related with the package but with Laravel itself.

This is an example of how you can achieve this

```php
$city = City::with('translations')->get();

$defaultTranslation = $city->getTranslation('en');

foreach(['es', 'fr', 'de']) as $otherLocale) {
    $otherTranslation = $defaultTranslation->replicate();
    $otherTranslation->locale = otherLocale';
    $otherTranslation->save();
}

```

**Comment by Gummibeer** [comment]
@Lloople thanks for answering! 💙
As an addition: keep in mind that you should reload the relationship on the main model after this loop. Otherwise you won't get these translations during this runtime on that main model.
