### ISSUE TITLE
Can I translate a model key which includes HTML Tags?

### ISSUE THREAD

**Issue by jazib93** [Astrotomic/laravel-translatable#111]
I've a model in which I need to store html content in the db and I want to translate that content but not the html tags. Is it possible with this package?

**Comment by Lloople** [comment]
This package is not intended to automatically translate content. 

This package allows you to define the relationships between the model and its translations, it adds methods to store and query them. 

If your translation contains HTML and you need an interface to manipulate them what you can do is to show different inputs, one per locale, and use tools like CKEditor to display it as an HTML editor.

**Comment by jazib93** [comment]
Great. Thank you
