### ISSUE TITLE
Correct usage with Nova

### ISSUE THREAD

**Issue by romanzipp** [Astrotomic/laravel-translatable#112]
First, thanks for your great work!
Is there any recommended way to integrate laravel-translatable into Nova?

I've currently added a panel per language into the Nova field declaration which works perfect if you're always writing articles in two languages.

In case I only want to write an article in English, the model creation process is as intended. When trying to update this model, the German translations get filled with the English translation content (I've enabled the fallback locale in the config file).

```php
public function fields(Request $request)
{
    return [
        ID::make()->sortable(),

        new Panel('English', [
            Text::make('Titel', 'title:en')->hideFromIndex(),
            Markdown::make('Inhalt', 'content:en')->hideFromIndex(),
        ]),

        new Panel('German', [
            Text::make('Titel', 'title:de')->hideFromIndex(),
            Markdown::make('Inhalt', 'content:de')->hideFromIndex(),
        ]),

        Text::make('Titel', 'title')->onlyOnIndex(),
    ];
}
```

Can I disable the fallback handling only in Nova or is there a more recommended way?

Thanks!

**Comment by romanzipp** [comment]
There's actually a package for that! Works perfectly with [yeswedev/ywd_nova-translatable](https://framagit.org/yeswedev/ywd_nova-translatable)

**Comment by adrienne** [comment]
@romanzipp - have you actually gotten the YWD package working for you in Nova? If so, could you contact me? Because I am trying to get it working and I can't. My email address is in my profile.

**Comment by Gummibeer** [comment]
I'm sorry but I don't have a nova license and haven't worked with it.
So I can't provide any information. If anything is required that can disable fallback logic during runtime I can investigate this.
