### ISSUE TITLE
[Question/Bug] Translatable Contract implementation...

### ISSUE THREAD

**Issue by FrancoisH** [Astrotomic/laravel-translatable#116]
Hi, the documentation says I should implement the contract in the model to be translated, like this :
```
use Astronomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;

class Category extends Model implements TranslatableContract
{
    use Translatable;
```

I'm using Laravel 6.x and when I do that I get an error :  `Interface Astronomic\Translatable\Contracts\Translatable' not found`

I thought the package where automatically registered in Laravel... Which they are to a point as just using the trait Translatable make it works, but the Interface won't.

Is this a bug, is there discrepancies in the documentation?

Thanks.

**Comment by Gummibeer** [comment]
The contract was implemented in:
https://github.com/Astrotomic/laravel-translatable/releases/tag/v11.1.0

Which version do you use?
```
composer show astrotomic/laravel-translatable
```

**Comment by FrancoisH** [comment]
@Gummibeer Version 11.6, the latest one.

**Comment by Gummibeer** [comment]
After reading your initial comment again it seems like you have a typo. 

```diff
- use Astronomic\Translatable\Contracts\Translatable as TranslatableContract;
+ use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
```

I hope it's not a copy paste one and the original issue is in the docs? :o If so please point me there.

https://github.com/Astrotomic/laravel-translatable/blob/v11.6.1/src/Translatable/Contracts/Translatable.php

**Comment by FrancoisH** [comment]
I missed the `astrotomic`... That's horrible... Thank you so much... I were going crazy with this.

**Comment by mohammedALhakmy** [comment]
I have some error to use the  astrotomic this error show in edit data and show error this 
class SettingHeader extends Model implements TranslatableContract{ 
not know the TranslatableContract can help me plase
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list'

update
  `setting_headers`
set
  `name` = this is name with englihs,
  `description` = < p > this is name with englihs < / p >,
  `setting_headers`.`updated_at` = 2023 -12 -16 08: 06: 05
where
  `id` = 2
