### ISSUE TITLE
using custom foreign key for translation table

### ISSUE THREAD

**Issue by keradan** [Astrotomic/laravel-translatable#117]
**Is it possible to set custom foreign key in translatable model?**
For example I have a model ShopCategory (with table "shop_categories"). While trying to get translation laravel looks for shop_category_id, but in translations table I set just simple category_id.

Migration indexes for ShopCategoryTranslation model looks like this

        Schema::create('shop_category_translations', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('category_id');
            $table->string('locale', 2)->index();

            $table->string('slug', 50);
            $table->string('title')->nullable();
            $table->text('description')->nullable();

            $table->unique(['category_id', 'locale']);
            $table->foreign('category_id')->references('id')->on('shop_categories')->onDelete('cascade');

            $table->timestamps();
        });

It wood be great, if model could automatically detect the name of foreign key, from the database index.

**Comment by Gummibeer** [comment]
Hey,
There's no easy way to get the foreign key by DB index or anything.
But you can define the translation foreign key by setting a property.

https://github.com/Astrotomic/laravel-translatable/blob/889f8b91f28a8a72873099cf452945adbd03dc9f/src/Translatable/Traits/Relationship.php#L52-L62

If it's not set we fallback to Laravel core functionality.

**Comment by keradan** [comment]
> Hey,
> There's no easy way to get the foreign key by DB index or anything.
> But you can define the translation foreign key by setting a property.
> 
> https://github.com/Astrotomic/laravel-translatable/blob/889f8b91f28a8a72873099cf452945adbd03dc9f/src/Translatable/Traits/Relationship.php#L52-L62
> 
> If it's not set we fallback to Laravel core functionality.

Oh great, thanks.

**Comment by MrJuliuss** [comment]
Hi, i got the same problem.

It would be nice to add the `$translationForeignKey` property to the documentation :+1:

**Comment by Gummibeer** [comment]
Hey @MrJuliuss , feel free to do so. :)

**Comment by HuyPham55** [comment]
Hey I got naive question: Where should $translationForeignKey be placed? In primary model class or translation one? I assume it should be in primary model but I'm not entirely sure
