### ISSUE TITLE
Allow new lines in translations

### ISSUE THREAD

**Issue by marijnkampf** [Astrotomic/laravel-translatable#118]
Currently translatable doesn't allow for new lines in translations. I have a few translations that include newlines and would like the code parser to pick these up.

There are two possible solution, the easiest would be to add the [s modifier](https://www.php.net/manual/en/reference.pcre.pattern.modifiers.php) to the regex pattern.
in the file `Core\CodeParses.php` change:     
`protected $pattern = '/([FUNCTIONS])\(\h*[\'"](.+)[\'"]\h*[\),]/U';`
to:
`protected $pattern = '/([FUNCTIONS])\(\h*[\'"](.+)[\'"]\h*[\),]/Us';

Or if you don't want to change the default behavior it could be made an optional settings in `config/laravel-translatable-string-exporter.php` which could default to false. Something along the lines of:
````
    // Indicates weather new lines are allowed in translations.
    'allow-newlines' => true,
````
 I'm happy to write this and submit a pull request if you like.

**Comment by Gummibeer** [comment]
Hey, it seems like you refer to another package. This package allows every possible value including ints, floats, JSON or whatever your database can handle.
Could it be that you mean this one?
https://github.com/kkomelin/laravel-translatable-string-exporter

**Comment by marijnkampf** [comment]
Doh, thanks!
