### ISSUE TITLE
replicateWithTranslations doesn't set the id of the new model

### ISSUE THREAD

**Issue by notflip** [Astrotomic/laravel-translatable#121]
I'm using `$newModel = $model->replicateWithTranslations();` 
What I see in my database is that a model is being replicated, so is the translation but the model_id of the relation is still set to the id of the original model

**Comment by Lloople** [comment]
I just tried this in a project of mine and it works as expected, remember you need to execute `$newModel->save()` after the replication

**Comment by Gummibeer** [comment]
@Lloople thanks for taking care! 😊
