### ISSUE TITLE
How to get results without translations?

### ISSUE THREAD

**Issue by rafailml** [Astrotomic/laravel-translatable#124]
I want go get category ids. Аnd I'm doing this:

```
return Category::select('id')
            ->where('parent_id', '=', $categoryId)
            ->get()
            ->toArray();
```

And I'm receiving:
id, name, slug, meta_description and all translations arrays

But I want to get only 'id's

How can I do that?
Is there a method withoutTranslations() ?  :)

**Comment by Gummibeer** [comment]
Hey,

I think that you've enabled translation autoloading.
You can disable it for this single query:
```php
Category::disableAutoloadTranslations();
// query
Category::defaultAutoloadTranslations();
```
https://github.com/Astrotomic/laravel-translatable/blob/32d060cfaee72f25097cef6e10b3d3c7e45a2d87/src/Translatable/Translatable.php#L72-L94

But I also recommend you to do `Category::where('parent_id', '=', $categoryId)->pluck('id')->toArray()` which doesn't create and fill a new model instance.

https://github.com/illuminate/database/blob/74cb8cb6a01e12c2b68618e23162efade7044c27/Eloquent/Builder.php#L680-L703

**Comment by rafailml** [comment]
That's it!!! Thank you very much!!!
