### ISSUE TITLE
Request update for Laravel 7

### ISSUE THREAD

**Issue by quangvision** [Astrotomic/laravel-translatable#127]
Hi Author,
  Can you please upgrade this package to support Laravel 7?
  Thanks :)

**Comment by Gummibeer** [comment]
Hey, will start upgrading today and this package will be top priority.
So there should be a new release until lunch (GMT+1). 😉

**Comment by Gummibeer** [comment]
It's released: https://github.com/Astrotomic/laravel-translatable/releases/tag/v11.8.0
