### ISSUE TITLE
Trashed Translations

### ISSUE THREAD

**Issue by lparede** [Astrotomic/laravel-translatable#130]
Hello.

If I want a certain post with translations in english, I will do this:

`$post= Post::translatedIn('en')->findOrFail(1);`

But what if I'm using soft deletes and I want a certain post with a trashed translation? Is there a way to do this?

Thank you.

**Comment by Gummibeer** [comment]
The translations are a default Eloquent relationship - you could add the `withTrashed()` scope call to the relationship - just override the `translations()` method.
