### ISSUE TITLE
How to add a column in select query from a translated table? 

### ISSUE THREAD

**Issue by iSarahSajjad** [Astrotomic/laravel-translatable#131]
`Category::select('uuid', 'logo', 'name')->paginate(20);`

Where name is from translated table, 
Right now its giving me an error on column not found

**Comment by u12206050** [comment]
Very important issue, I have the same issue when trying to filter on a translated property eg.
`Post::where('slug', $slug)->first()` 
where `slug` is translated.

**Comment by u12206050** [comment]
Ah found my answer, don't know if it fits for @iSarahSajjad 
[DOCS](https://docs.astrotomic.info/laravel-translatable/faq#how-can-i-select-a-model-by-translated-field)
Post::whereHas('translations', function ($query) {
    $query
        ->where('locale', 'en')
        ->where('title', 'My first post');
})->first();
