### ISSUE TITLE
Translated attributes won't save with mass update (v11.5 - Laravel 5.6)

### ISSUE THREAD

**Issue by weidmaster** [Astrotomic/laravel-translatable#132]
**Describe the bug**
When using the correct version of the package for Laravel 5.6 (v11.5), the translated attributes are not saved in the database when using mass update. Trying to use any other version fails when issuing composer update

**To Reproduce**
- Setup everything according to the documentation (https://docs.astrotomic.info/laravel-translatable/installation)
- Setup a form according to the documentation, using the array variant for an Update Request (https://docs.astrotomic.info/laravel-translatable/usage/forms#request-as-array-syntax)
- Load the Model according to the following:
```$data = Product::findOrFail($id);```
- Capture the request according to the following:
```$input = $request->all();```
- Call the update method as the following:
```$data->update($input);```

**Expected behavior**
- Upon updating the model the translated attributes should be saved in the database in the translations table.

**Versions**
- PHP: 7.4
- Database: MariaDB 15.1
- Laravel: 5.6
- Package: "astrotomic/laravel-translatable": "11.5.*"

**Additional context**
- changing the following line of src/Translatable/Translatable.php in the method fill(), line 104, seems to solve the problem:

Original
```$this->getTranslationOrNew($key)->fill($values);```

Edited
```$this->getTranslationOrNew($key)->fill($values)->save();```

- Debugging with Xdebug shows that the attributes are indeed filled in the Translated model instance, but the data is never saved in the database. According to Laravel documentation, the saved event of a Model is not called with massive updates. (https://laravel.com/docs/5.6/eloquent#updates).

- Using the other documented method $data->fill($attributes)->save(); does not work as well. So again it seems to be related to Laravel itself.

- Getting the translated attribute works as intended. Just the saving is the issue

**Exception**
Not applicable. No Exception is throw

**Stack Trace**
Not applicable. No Exception is throw

**Comment by Gummibeer** [comment]
At first thanks for this very complete issue! 🤩

Could you debug the `saved` hook and the called method?
https://github.com/Astrotomic/laravel-translatable/blob/d1496d1f53e40ce6ceb689aa75befea4818211f1/src/Translatable/Translatable.php#L29-L35
I would like to know what does not work. Because you are the first and it's the fundamental core of this package I still believe that it's somehow related to your setup. My first idea would be any other event running before returns `false` and prevents other events from running.

Regarding the hint for massive updates: that's only the case for DB side ones. You are doing a simple mass update, so at all the event should be fired.

**Comment by weidmaster** [comment]
And thanks for replying so fast! It is nice to see the developers taking care of their products even with the earlier versions. I did a screencast with the debug session. I think you can see better that the method asked is not called at all.

Maybe it is my setup but I don't know how to debug the whole chain of calls from Eloquent events. I did get to see the save method from the Model itself is called in the vanilla Eloquent update() method. The line is literally like fill()->save() and that is why I tried to edit like that.

Please take a look at the capture and let me know how to proceed with the debug 😄 

https://drive.google.com/file/d/1_GhuzNcNwrP8_YV1ZicrCmHqrqvqYsZv/view?usp=sharing

**Comment by Gummibeer** [comment]
Hey,

have you overridden the `boot()` method in your product model without calling `parent::boot()`? The core is responsible to call the trait boots and this is possible since Laravel 5.0.

In general I can only recommend you to upgrade your app (this shouldn't solve this issue) https://laravelshift.com will help you with this task.

**Comment by weidmaster** [comment]
I will take a look if this method is overloaded. In the meantime I had another issue so it seems to be related to the setup indeed. I just tried to add more locales and fields to my form and it is sending the null values because I didn't type anything. Even though it should send empty strings insteads. I also had to add the line

```$this->saveTranslations();```

before the call to parent::fill() because when doing the regular ->save() one it is not adding the product_id foreign key field and it was failing.

Doing so makes it fail with an error from the QueryBuilder as it can't insert a null value in the fillable property and fails with a constraint issue.

Well I can't refactor the app for now so I will do something to make iit work eventually. But thanks for helping debugging this

**Comment by Gummibeer** [comment]
Yes, your `__construct()` isn't compatible with the core and doesn't call `parent::__construct()`.

That's the core construct:

```php
    public function __construct(array $attributes = [])
    {
        $this->bootIfNotBooted();

        $this->initializeTraits();

        $this->syncOriginal();

        $this->fill($attributes);
    }
```

Notice the `$this->bootIfNotBooted();` call - that's the important one.

Your construct should be adjusted to:

```php
public function __construct(array $attributes = []) 
{
    parent::__construct($attributes);

    $currentUrl = str_replace(
        ['http://','https://'],
        '',
        url()->current()
    );
        
    $this->storeSettings = GeneralSetting::whereRaw("'{$currentUrl}' LIKE CONCAT(domain,'%')")->first();
        
    if (!$this->storeSettings || empty($this->storeSettings->domain)) {
        $this->storeSettings = GeneralSetting::where('is_default',1)->firstOrFail();
    }
}
```

**Comment by weidmaster** [comment]
Yes that fixed the behaviour! I thought the Model didn't have a parent constructor at all (like Controller), so I never bothered checking. It is working! Thank you very much.
