### ISSUE TITLE
how i can change translatable.locales in fly

### ISSUE THREAD

**Issue by vahidalvandi** [Astrotomic/laravel-translatable#137]
how i can change translatable.locales in fly  ??

please show me how i can this
https://docs.astrotomic.info/laravel-translatable/package/locales-helper#all

and set locales in fly?

thank you

**Comment by Gummibeer** [comment]
Hey,
You can use the `load()` or `add()` method to adjust the available locales on runtime.

**Comment by vahidalvandi** [comment]
`dd(load());
`
now work .

**Comment by Gummibeer** [comment]
https://docs.astrotomic.info/laravel-translatable/package/locales-helper#load
https://docs.astrotomic.info/laravel-translatable/package/locales-helper#add-string-usdlocale

```php
config()->set('translatable.locales', ['en', 'de', 'fr', 'it']);
app(\Astrotomic\Translatable\Locales::class)->load();

// or
app(\Astrotomic\Translatable\Locales::class)->add('de');
```

**Comment by vahidalvandi** [comment]
thank you. do i can change fallback ??

**Comment by vahidalvandi** [comment]
ttha

> https://docs.astrotomic.info/laravel-translatable/package/locales-helper#load
> https://docs.astrotomic.info/laravel-translatable/package/locales-helper#add-string-usdlocale
> 
> ```
> config()->set('translatable.locales', ['en', 'de', 'fr', 'it']);
> app(\Astrotomic\Translatable\Locales::class)->load();
> 
> // or
> 
> app(\Astrotomic\Translatable\Locales::class)->add('de');
> ```

thank you
