### ISSUE TITLE
RuleFactory doesn't parse Rule::unique second parameter

### ISSUE THREAD

**Issue by kamranata** [Astrotomic/laravel-translatable#140]
I am trying to validate with **Rule::unique** ,  if it doesn't replace different column argument.

```
RuleFactory::make([
            '%name%' => [
                'required',
                Rule::unique('category_translation', '%name%')
            ],
        ])
```

Output is:

```
array:1 [▼
  "en.name" => array:2 [▼
    0 => "required"
    1 => Illuminate\Validation\Rules\Unique {#550 ▼
      #ignore: null
      #idColumn: "id"
      #table: "category_translation"
      #column: "%name%"
      #wheres: []
      #using: []
    }
  ]
]
```

#column must be "en.name"

**Comment by PeterDanielss** [comment]
Last "s" of category_translations is missing. (y)

**Comment by kamranata** [comment]
> Last "s" of category_translations is missing. (y)

Thanks, but this is a typo. Not the solution to the error I mentioned above.

**Comment by Gummibeer** [comment]
Hey,
that's intended behavior - only `strings` are parsed and strings in an array.
But the unique rule wouldn't work anyways because you want to query by value of `locale` column.
So right now this isn't possible.

**Comment by PeterDanielss** [comment]
`Rule::unique('category_translations', 'name')->where(function ($query) {
	return $query->where('locale', 'en');
})`

Have good day 👍

**Comment by kamranata** [comment]
> `Rule::unique('category_translations', 'name')->where(function ($query) { return $query->where('locale', 'en'); })`
> 
> Have good day 👍

@PeterDanielss thank you for reply. I also know this "solution". But I want to use  RuleFactory's way.

**Comment by nekooee** [comment]
> `Rule::unique('category_translations', 'name')->where(function ($query) { return $query->where('locale', 'en'); })`
> 
> Have good day 👍

how to use ignore for an update??

**Comment by nekooee** [comment]
> `Rule::unique('category_translations', 'name')->where(function ($query) { return $query->where('locale', 'en'); })`
> 
> Have good day 👍

how to use ignore for an update??

**Comment by nekooee** [comment]
> > `Rule::unique('category_translations', 'name')->where(function ($query) { return $query->where('locale', 'en'); })`
> > Have good day 👍
> 
> how to use ignore for an update??

@PeterDanielso 
@kamranata

**Comment by PeterDanielso** [comment]
Hello, i think u need to fetch the ids of every translation, in mi case, working inside controller with model sent from route.

Example:

```
public function update(Request $request, Category $category)
{
	$translation_ids = $category
		->translations
		->pluck('id', 'locale')
		->toArray();		
		
	$data = $request->validate([
		'en.name' => [
			'required',
			Rule::unique('category_translations', 'name')->where(function ($query) {
				return $query->where('locale', 'en');
			})->ignore($translation_ids['en'])
		]
	]);
	
	
	$category->update($data);	

}
```

**Comment by AbdallaMohammed** [comment]
Hi, I think this is old issue, but I was able to figure a way to fix that issue by creating a helper function

`
if (! function_exists('app_translations_unique')) {
    /**
     * @param string $table
     * @param string $field
     * @param array $ignore
     * @return array
     */
    function app_translations_unique(string $table, string $field, array $ignore = [])
    {
        $rules = [];
        foreach (array_keys(config('locales')) as $locale) {
            $rules["$field:$locale"] = $rule = Rule::unique(Str::singular($table).'_translations', $field)->where(function ($query) use ($locale) {
                $query->where('locale', $locale);
            })->ignore($ignore[$locale] ?? []);
        }

        return $rules;
    }
}
`

and I'm using this helper like this

`
    /**
     * Get the create validation rules that apply to the request.
     *
     * @return array
     */
    public function createRules()
    {
        return RuleFactory::make(array_merge([
            '%name%' => ['required', 'string', 'max:255'],
        ], app_translations_unique('companies', 'name')));
    }
`

For ignoring IDs thanks for @PeterDanielso 

`
    /**
     * Get the update validation rules that apply to the request.
     *
     * @return array
     */
    public function updateRules()
    {
        return RuleFactory::make(array_merge([
            '%name%' => ['required', 'string', 'max:255'],
        ], app_translations_unique('companies', 'name', $this->route('company')->translations->pluck('id', 'locale')->toArray())));
    }
`
