### ISSUE TITLE
Is this the right way to use the fill() to save a translation data?

### ISSUE THREAD

**Issue by notflip** [Astrotomic/laravel-translatable#144]
I have a Banner and BannerTranslation model, I'm trying to use fill() as stated here: 
https://docs.astrotomic.info/laravel-translatable/usage/forms#forms

To fill translation data when seeding a Banner, this is the code I'm using
```

 $banner = Banner::create([
            'working_title' => 'Square Banner',
            'site' => 'vilt',
            'format' => 'square'
        ]);

        $banner->fill([
            'nl' => [
                'title' => 'Square Banner',
                'link' => 'https://en.link',
                'online' => 1
            ]
        ]);

        $banner->save();
```

But a translation is not being made, any idea if I'm missing something?
Thank you

**Comment by Gummibeer** [comment]
Hey, at first you can combine these calls - add the `nl` array to the `create()` one and you don't have to save twice.
Next, the array structure you pass in is right.
Have you followed all installation steps? Added `nl` as locale and listed the three attributes as translatable?

**Comment by notflip** [comment]
@Gummibeer Thanks for getting back this fast, is the $fillable attribute mandatory on the translation model, or is using an empty $guarded attribute okay? Do you mean if I added 'nl' to the config?

**Comment by notflip** [comment]
This is the code I'm using at the moment, I'm using $fillable on the translation model but it's still not working, the model is being made, the translation is not.

```
Banner::create([
            'working_title' => 'Square Banner',
            'site' => 'vilt',
            'format' => 'square',
            'nl' => [
                'title' => 'Square Banner',
                'link' => 'https:/nll.link',
                'online' => 1
            ]
        ]);
```

This is my Model
```
class Banner extends Model
{
    use Translatable;

    protected $guarded = [];

    public $translatedAttributes = ['title', 'slug', 'image_id', 'link', 'online'];
}
```

Translation Model
```
class BannerTranslation extends Model
{
    protected $fillable = ['title', 'slug', 'image_id', 'link', 'online'];

    public function banner()
    {
        return $this->belongsTo(Banner::class);
    }
}
```

**Comment by notflip** [comment]
Hmh I think I found the solution, our package was overwriting some methods of yours, sorry for wasting your time! I have someone to be pissed on
