### ISSUE TITLE
Hardcoded locale key in Relationship trait

### ISSUE THREAD

**Issue by NEDIX** [Astrotomic/laravel-translatable#145]
**Describe the bug**
The Relationship trait makes use of hardcoded locale keys in the translation and localeOrFallback methods.

**To Reproduce**
Use a foreign key other than locale on your translations table to reference the languages table.

**Expected behavior**
The locale_key configuration value to be used in the query.

**Versions**
- Package: 11.8

**Exception**
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'locale' in 'where clause'`

**Comment by Gummibeer** [comment]
Hey,
thanks for reporting.
It's fixed in [v11.8.1](https://github.com/Astrotomic/laravel-translatable/releases/tag/v11.8.1).
