### ISSUE TITLE
Default translate if null

### ISSUE THREAD

**Issue by Zero-jano** [Astrotomic/laravel-translatable#147]
Hi 
i want to ask you if for example locale app = Spanish and don't found Spanish translate or null field can i set default translate from English .

**Comment by Gummibeer** [comment]
Hey,
yes - we allow fallbacks.
https://docs.astrotomic.info/laravel-translatable/package/fallback-locale
There's also an option to do property/attribute level fallbacks.
https://docs.astrotomic.info/laravel-translatable/package/fallback-locale#for-properties
So you can get the fallback description even if the title is translated - just an example. There's also a method that allows you to customize the logic what's handled as empty translation. By default we use `empty()` - so every falsy value. But if you want to allow `0` or an empty JSON array or anything similar you can customize this.
