### ISSUE TITLE
Return value of App\Post::locale() must be of the type string, null returned

### ISSUE THREAD

**Issue by BAKTETE** [Astrotomic/laravel-translatable#15]
**Describe the bug**
just upgraded from dimsav to astrotomic everything used to work fine but now i'm getting this error : Return value of App\Post::locale() must be of the type string, null returned at vendor\astrotomic\laravel-translatable\src\Translatable\Translatable.php

**To Reproduce**
retrieving adding updating 

**Screenshot**
![Annotation 2019-06-22 004247](https://user-images.githubusercontent.com/27772375/59956199-c699af80-9486-11e9-80db-698891b28481.jpg)

**Versions (please complete the following information):**
- PHP: 7.3.6
- Database: Mysql 8.0.16
- Laravel: 5.8.24
- Package: v11.1.0

**Comment by BAKTETE** [comment]
The session locale was empty that's what's triggering the error i managed to solve by adding the following code in `AppServiceProvider.php` inside method ` boot()` :
```

public function boot()
    {
        Schema::defaultStringLength(400);
        
       //check if current locale is empty if so a default locale must be provided 
        if(!Session::has('locale'))
        {
            session(['local' => 'fr']);
            App::setLocale('fr');
            Carbon::setLocale('fr');
        }
        setlocale(LC_ALL, config('app.locale') . '.utf8');
        Carbon::setLocale(config('app.locale'));

    }
}
```
any other suggestions will be appreciated

**Comment by Gummibeer** [comment]
Hey,

by default Laravel should have a locale at every time - except you set the locale to `null`. The `config('app.locale')` is used by default for the whole app - this includes the translator which is used in `Locales::current()`.
https://github.com/Astrotomic/laravel-translatable/blob/e3b20dfddd4c33a103c744b15cfbe4e253cb18cd/src/Translatable/Locales.php#L46-L49
So we have two things:
1. the `Locales::current()` is missing the return type-hint `string`
2. in your app the translator doesn't have a locale

Could you debug/dump the two possible return values of the `Locales::current()` method? Just put a `dump()` with both values inside the method.

**Comment by BAKTETE** [comment]
@Gummibeer 
`dump($this->config->get('translatable.locale'));` output : "fr"
`dd($this->translator->getLocale());` output : null

**Comment by Gummibeer** [comment]
Ok, so you found a solution for your app or do we have to change something in the package?
If I understood it right everything fine now?

**Comment by BAKTETE** [comment]
@Gummibeer the solution is to update a line in translatable.php file inside config
`'locale' => null,`
to
`'locale' => 'fr',`
your approach of 
```
dump($this->config->get('translatable.locale'));
dd($this->translator->getLocale());
```
lead to that solution all works fine now thank you
