### ISSUE TITLE
Performance problem - so many queries and I can't cache them

### ISSUE THREAD

**Issue by core45** [Astrotomic/laravel-translatable#154]
**Describe the bug**
The package generates a lots of extra queries even the main query is cached.

**To Reproduce**
`$country` = Country::whereTranslation('slug', $countrySlug)->with('destinations')->first();`
or 
```
$country = Cache::remember('catalog_country'), now()->addMinutes(60), function () use ($countrySlug) {
     Country::whereTranslation('slug', $countrySlug)->with('destinations')->first();
});
```
Produces almost the same amount of queries mostly like this:

`select` * from `destinations_translations` where `destinations_translations`.`destination_id` = 1 and destinations_translations`.`destination_id` is not null`

Of course main query is cached but the remaining hundreds are killing the server. 
Is it possible and how to cache the rest?

**Versions (please complete the following information)**
- PHP: 7.3
- Database: Mysql 5.7
- Laravel: 6.18.14
- Package:

**Comment by Gummibeer** [comment]
Hey,
You will have to eager load the translations of destinations and possibly also of countries.
```php
with('translations', 'destinations', 'destinations.translations')
```
This should help to reduce the amount of queries and cache the translations.

Something besides this package: have you seen this?
https://github.com/Astrotomic/laravel-cachable-attributes
Right now it's not up-to-date and not compatible with Laravel 7. But would this package be useful for you? Or do you cache the query result outside of a model?

**Comment by core45** [comment]
It helped. Now it works like a charm!
THANK YOU VERY MUCH!

I also give laravel-cachable-attributes  a try.

You saved my day.
