### ISSUE TITLE
translation ilike

### ISSUE THREAD

**Issue by applyACS** [Astrotomic/laravel-translatable#155]
I want to be able to use 'ilike' for where translation.
Maybe have a method like 'whereTranslationLike' but using 'ilike'.
Did not see something like this in documentation

**Comment by Gummibeer** [comment]
Hey,
you can use the available scope builder method to create this scope by your own.
```php
public function scopeWhereTranslationIlike(Builder $query, string $translationField, $value, ?string $locale = null)
{
    return $this->scopeWhereTranslation($query, $translationField, $value, $locale, 'whereHas', 'ILIKE');
}
```
Right now I prepare for v12 and it's not clear how the scopes will be kept - related to #129 . That's why I don't want to add this scope right now.
