### ISSUE TITLE
How can I executing queries to only one?

### ISSUE THREAD

**Issue by jeanali** [Astrotomic/laravel-translatable#157]
I have Area Model translate to (ar, en) everything is good **but**  BUT when I open the debugger I found there is 21 queries run!!

<img width="1437" alt="Screen Shot 2020-06-26 at 9 43 08 PM" src="https://user-images.githubusercontent.com/67483209/85895142-c1d8ab80-b7fe-11ea-8083-9523992f8065.png">

my foreach:

<img width="611" alt="Screen Shot 2020-06-26 at 10 46 51 PM" src="https://user-images.githubusercontent.com/67483209/85895228-f0ef1d00-b7fe-11ea-9df5-864f94053f30.png">

my code in controller:

<img width="762" alt="Screen Shot 2020-06-26 at 10 48 00 PM" src="https://user-images.githubusercontent.com/67483209/85895319-2267e880-b7ff-11ea-978d-900d19b433b0.png">

**Comment by Gummibeer** [comment]
Hey,

you should eager load the translations relationship on the collection of area models.
This will execute only one query for all areas and translations will work.

```php
$areas->load('translations');
```
