### ISSUE TITLE
Error when store the data

### ISSUE THREAD

**Issue by MohammadNehru** [Astrotomic/laravel-translatable#158]
Hello,
I'm getting this error when trying to add data to the database.

_**Astrotomic\Translatable\Exception\LocalesNotDefinedException
Please make sure you have run "php artisan config:publish astrotomic/laravel-translatable" and that the locales configuration is defined.**_

_**store function**_
```
        $data = [
            'en' => [
                'title'       => $request->input('en_title'),
                'text' => $request->input('en_text')
            ],
            'ar' => [
                'title'       => $request->input('ar_title'),
                'text' => $request->input('ar_text')
            ],
        ];

        Section::create($data);
        return redirect()->route('sections.index');
```

**Comment by MohammadNehru** [comment]
```
php artisan config:cache
```
And the problem will be solved.

**Comment by Gummibeer** [comment]
Hey,
in your case it was probably an outdated cached config. But you pointed me to another "bug". The exception message was totally wrong!
There never was a `artisan config:publish` command. :D 
It's fixed in https://github.com/Astrotomic/laravel-translatable/releases/tag/v11.8.3
