### ISSUE TITLE
How to return English "en" as a default language if translate is NULL (not set)?

### ISSUE THREAD

**Issue by Nizaralmohammad** [Astrotomic/laravel-translatable#161]
<img width="337" alt="Screen Shot 2020-07-27 at 23 07 30" src="https://user-images.githubusercontent.com/22705325/88587915-6567e680-d05f-11ea-8a6a-ee5d287b8eb2.png">

```json
{
    "id": 6,
    "slug": "train2",
    "parent_id": 2,
    "position": null,
    "is_active": 1,
    "created_at": "2020-07-25T20:03:55.000000Z",
    "updated_at": "2020-07-25T20:03:55.000000Z",
    "items": [],
    "name": null,
    "translations": [
        {
            "id": 4,
            "category_id": 6,
            "locale": "en",
            "name": "Train2",
            "created_at": null,
            "updated_at": null
        }
    ]
}
```

in the above example code, I have used translation to switch between English "en" and Turkish "tr", and I didn't
write any translation related to Turkish, so when I choose "tr" language it gives me the name filed is null.
so how can I make the default translation language to be "en" if I have any NULL values.

**Comment by Gummibeer** [comment]
Hey,

have you checked the documentation regarding fallback locale?
https://docs.astrotomic.info/laravel-translatable/package/fallback-locale

In v12 the behavior will change in the package/core and allow much more flexibility but will kind of be backwards compatible. #129
