### ISSUE TITLE
Not updating with Nova

### ISSUE THREAD

**Issue by u12206050** [Astrotomic/laravel-translatable#162]
**Describe the bug**
I am using this with Nova, but none of the translatable fields seem to be updating.

**To Reproduce**
Install Nova v3
Setup a model and resource that is translatable
Create a new resource, and then try and update its fields
Only non-translatable fields are updated without any error

**Expected behavior**
All fields are updated

**Versions (please complete the following information)**
- PHP: 7.4
- Database: mysql
- Laravel: 7.22
- Package: Nova v3.8.2

**Exception**
None

**Comment by u12206050** [comment]
Create a [PR #163](https://github.com/Astrotomic/laravel-translatable/pull/163) that fixes this issue

**Comment by u12206050** [comment]
Any updates on publishing the PR?

**Comment by Gummibeer** [comment]
Hey,

sorry for the delay. And thanks for your work.

Except of the failing tests I have some fundamental questions about the issue.


So far I've seen in the PR the issue is that Nova uses the `translation` (singular) relation instead of the `translations` (original) one!?
If that's the case how's your Nova setup? Do you use any package make this package work with Nova?

**Comment by u12206050** [comment]
Hei, I use this with my own personal version of [switch-locale](https://github.com/u12206050/switch-locale)

**Comment by u12206050** [comment]
Btw, I have refactored and cleaned up the code a bit. It seems like Nova uses the singular due to it being just one field and it doesn't see it as a direct relationship, probably due to the abstraction that laravel-translatable does.

**Comment by jezzdk** [comment]
@u12206050  Did you find a solution to this?

**Comment by u12206050** [comment]
Yes am using the pull request that I made. ->translation

**Comment by Gummibeer** [comment]
Seems that this relates to #215 and is based in the usage of `translation` instead of `translations`.
There's a package for nova that doesn't do anything related to this: https://github.com/yeswedev-team/ywd_nova-translatable
So it's not a general conflict with nova.
