### ISSUE TITLE
Is it possible to disable the translation fallback during a query?

### ISSUE THREAD

**Issue by enkota** [Astrotomic/laravel-translatable#166]
Hey,

I have enabled fallbacks so that if a `Post` language is empty, it'll fallback to English.

This is great, however, on my admin I need to determine if that translation exists yet. The issue is that while getting a locale, it'll return the English (fallback) fields. 

Is there a method maybe around `app()->setLocale($request->lang);` that I can determine if a fallback is being returned or the translated record? Ideally, I'd like the public to see the fallback on the front-end, but no fallback in the admin interface.

Cheers!

**Comment by Gummibeer** [comment]
Hey,

you can check if the model has a translation in a given locale [hasTranslation()](https://docs.astrotomic.info/laravel-translatable/package/methods#hastranslation-string-usdlocale-null)
Or explicitly use the [translate($locale, false)](https://docs.astrotomic.info/laravel-translatable/package/methods#translate-string-usdlocale-null-bool-usdwithfallback-false)  method.

If you haven't enabled property fallback you could also use `$post->{'title:de'}` - so attribute with an explicit locale.

**Comment by enkota** [comment]
Hey @Gummibeer thanks for the quick response!

I think I'll go with `$post->translate('it', true);` -- that looks like the perfect solution 👍

Thanks :)
