### ISSUE TITLE
cannot store or update fields of translatedAttributes array

### ISSUE THREAD

**Issue by miladshm** [Astrotomic/laravel-translatable#167]
**Describe the bug**
when I place a column name in translatedAttributes array no longer can store into that column.

**To Reproduce**

 Article Model:

use Astrotomic\Translatable\Translatable;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Article extends Model implements TranslatableContract
{
   use Sluggable, Translatable;

   public $translatedAttributes = ['title','body', 'summery'];

   protected $fillable = ['title','body', 'summery', 'slug', 'user_id', 'is_active', 'publish_at']; 
   // it's doesn't work either when translated attributes not placed in $fillable

// my model relations...
}
**Screenshots**

**Versions (please complete the following information)**
- PHP: 7.4.4
- Database: mysql
- Laravel: 7.25
- Package: 11.8.3

**Exception**
Field 'title' doesn't have a default value

**Comment by danut3101** [comment]
same here.
PHP 7.4.0
Database mysql
Laravel 7.24
Package 11.9

**Comment by Gummibeer** [comment]
@miladshm if I get your issue right you try to have the same column in your main models table and also in the translation table? This doesn't work and isn't expected to do - data normalization.

@danut3101 do you try the same or what's your issue? If it's not exactly the same please open a new issue. 🙂

**Comment by sanneterpstra** [comment]
Same here..
PHP 7.4.5
MySQL
Laravel 8.0
Package 11.9

**Comment by Gummibeer** [comment]
@sanneterpstra please open a new issue with a clear description as this issue is stale and no one has described it in more detail.
