### ISSUE TITLE
withTranslation scope does not return the default translation

### ISSUE THREAD

**Issue by Smmw** [Astrotomic/laravel-translatable#168]
**Describe the bug**

```
//Set the locale
App::setLocale('mi');

//Loa Modal with translation
Modal::withTranslation()->get();
```
It only returns the default translation `en`.
It was able to return the desired translation with default translation.

Previous result:
```
[{
    title: 'title in mi languge',
    description: 'description in mi language',
    translations: [{
         title: 'title in default languge',
         description: 'description in default language',
    }]
}]
```

Current result: 
```
[{
    title: 'title in default languge',
    description: 'description in default language',
    translations: [{
         title: 'title in default languge',
         description: 'description in default language',
    }]
}]
```

**Expected behaviour**
```
[{
    title: 'title in mi languge',
    description: 'description in mi language',
    translations: [{
         title: 'title in default languge',
         description: 'description in default language',
    }]
}]
```

**To Reproduce**
![image](https://user-images.githubusercontent.com/3632980/90738988-a384bd00-e322-11ea-8b28-4312e089f255.png)

Database: 
![image](https://user-images.githubusercontent.com/3632980/90739874-e181e100-e322-11ea-8807-7022784a02cf.png)
![image](https://user-images.githubusercontent.com/3632980/90737572-412bbc80-e322-11ea-944a-2761cdefefe5.png)

**Versions**
- PHP: 7.4.8
- Database: Tested on Mysql 8.0, 5.7 and 5.8
- Laravel: 6.18.35
- Package: 11.8.3

**Comment by assoft** [comment]
Is there any solution?

**Comment by henze-housepedia** [comment]
Any updates on this? as it is quite annoying in combination with Twill,

The workaround for non twill users would be creating an attribute getter (getTranslatableAttribute), but with Twill this just breaks the translation.

**Comment by Smmw** [comment]
@henze-housepedia What I did is to get all the translations and filter out the unneeded translations.
