### ISSUE TITLE
config/translatable.php : locales returns null

### ISSUE THREAD

**Issue by ZainabEid** [Astrotomic/laravel-translatable#170]
**Bug Description**
I tried to use spatie/laravel-translatable and I removed it with command
`composer remove spatie/laravel-translatable`
I deleted config/ translatable.php file by hand

I installed astrotomic/laravel-translatable following the installation instructions in this link 
https://docs.astrotomic.info/laravel-translatable/installation 

I edit config / translatable.php file locale and locales array

```
'locales' => [
        'ar',
        'en',
        'tr',
    ],
 'locale' => 'ar',
```

**Bug:1 I tried to access locales but it returns null**
config('translatable.locales') returns null
current() returns null as well

I tried to enter the locales in array variable instead of getting them from config/translatable.php
```
  @php
 // $locales = config('translatable.locales') ;
$locales=['ar','en','tr'];
@endphp

@foreach ( $locales as $locale )
<div class="form-group">
<label for="name">@lang('site.'.$locale.'.name')</label>
<input type="name" class="form-control" name="{{ $locale }}[name]"
placeholder=" @lang('site.enter-name')" value="{{ old( $locale.'.name') }}">
</div>
@endforeach
```

```
// CategoryController.php

    public function store(Request $request)
    {
        $request->validate([
            'ar.*' => 'required',
        ]);

        Category::create($request->all());
        session()->flash('success', __('site.added-successfuly'));
        return redirect()->route('adminDashboard.categories.index');
    }
```
**Bug 2: when i run application it throws the following exception:**
>Please make sure you have run `php artisan vendor:publish --provider="Astrotomic\Translatable\TranslatableServiceProvider"` and that the locales configuration is defined.

**Expected behavior**
to find three values in category_translations with the same category_id and 3 different locale values (ar,en,tr)

**Screenshot**
![exceptionscreenshoot](https://user-images.githubusercontent.com/62047030/91468177-e8b06e00-e891-11ea-972f-75c4b28da5ee.png)

**Models**
```
// Category Model
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;

class Category extends Model
{
    use Translatable;

    public $translatedAttributes = ['name'];
}
```
```
//CategoryTranslation Model

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CategoryTranslation extends Model
{
    public $timestamps = false;
    protected $fillable = ['name'];
}
```

**Versions**
- PHP: 7.2.5
- Database: mySql
- laravel/framework: 7.24
- Package: astrotomic/laravel-translatable: 11.8
-  mcamara/laravel-localization: 1.5

**Comment by Gummibeer** [comment]
Hey,
this is very likely because you have a cached config.
You should run `php artisan config:clear` to clear your config cache.

**Comment by ZainabEid** [comment]
it works !!  
thanks  alot

**Comment by mohamedkaram10** [comment]
> Hey, this is very likely because you have a cached config. You should run `php artisan config:clear` to clear your config cache.

but don't works with me
