### ISSUE TITLE
Fallback locale gets ignored

### ISSUE THREAD

**Issue by lindo-llc** [Astrotomic/laravel-translatable#172]
**Describe the bug**
The fallback locale is ignored

**To Reproduce**
 Russian translation does not exist in the database
`Category::first()->translate('ru')->name`

**Expected behavior**
An English translation should be returned since it IS defined in the database and configuration file configured to use fallback locale.

**Versions**
- PHP: 7.4.9
- Database: MySQL
- Laravel: 7.26.1
- Package: astrotomic/laravel-translatable

**Exception**
Trying to get property 'name' of non-object

**Stack Trace**
[https://flareapp.io/share/DPylQRm9#F48](https://flareapp.io/share/DPylQRm9#F48)

**Comment by lindo-llc** [comment]
Solved it by using a custom trait to override `translate` function

`
use Astrotomic\Translatable\Translatable as AstrotomicTranslatable;

trait Translatable
{
    use AstrotomicTranslatable;


    /**
     * Translate override to use fallback always
     *
     * @param string|null $locale
     * @param boolean $withFallback
     * @return Model|null
     */
    public function translate(?string $locale = null)
    {
        return $this->getTranslation($locale, true);
    }

`

**Comment by Gummibeer** [comment]
Hey,

this already exists as `translateOrDefault()` method. All this behavior is also fully described in the docs.
You could also set the locale as app locale and just do `$category->name` in this case it will also use the fallback configuration.
