### ISSUE TITLE
php artisan route:cache - 404 page not found

### ISSUE THREAD

**Issue by SarajevoNo1** [Astrotomic/laravel-translatable#182]
Hi dear,

When I make php artisan route:cache in my app after installing your package , I got error 404 and cannot open any links, what should be solution ?!

Thanks!

**Comment by Gummibeer** [comment]
Hey,

I could imagine that it's not a real 404 but there's an underlying exception. Could you check your logs and possibly dump the exception in your exception handler if it's possibly ignored.

This package does nothing with your routing. The only thing could be a missing, cached, wrong configuration throwing an exception on package load.
You could also run `artisan config:clear` to check if it's an outdated cached configuration.
