### ISSUE TITLE
Cannot validate inputs

### ISSUE THREAD

**Issue by ArtMin96** [Astrotomic/laravel-translatable#183]
Hi.

Thanks for this amazing package. It helps me a lot!

I don't know why but validation not working for me. That's my code.

create.blade.php
```
@foreach(config('app.locales') as $key => $locale)
    <div class="card-body switch-translatable-fields p-0 d-none {{ $locale }}-form @if($key == 0) d-block @endif">
        <div class="form-group">
            <label class="required" for="{{ $locale }}_name">{{ trans('Page title') }} ({{ \Illuminate\Support\Str::upper($locale) }})</label>
            <input class="form-control @error($locale.'_name') is-invalid @enderror" type="text" name="{{ $locale }}_name" id="{{ $locale }}_name" value="{{ old($locale.'_name') }}">

            @error($locale.'_name')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
@endforeach
```

Controller
`RuleFactory::make([
            'translations.%name%' => 'required|string',
        ]);`

I hope you can help me. Thanks!

**Comment by Gummibeer** [comment]
Hey,

I'm on the road right now and nearly never use the rule factory but I think that I spot two issues.
Your input name is `en_name` (underscore) but you should use `en[name]` (html array) to receive it as an array and use `%name` as key in the rule factory to generate rules for `en.name` (array dot notation).

So fixing your input name in html to `$locale.'[name]'` and the rule key to `%name%` without prefix should solve your issue.

**Comment by ArtMin96** [comment]
> Hey,
> 
> I'm on the road right now and nearly never use the rule factory but I think that I spot two issues.
> Your input name is `en_name` (underscore) but you should use `en[name]` (html array) to receive it as an array and use `%name` as key in the rule factory to generate rules for `en.name` (array dot notation).
> 
> So fixing your input name in html to `$locale.'[name]'` and the rule key to `%name%` without prefix should solve your issue.

**Comment by ArtMin96** [comment]
It still not working.

```
@foreach(config('app.locales') as $key => $locale)
                                                <div class="card-body switch-translatable-fields p-0 d-none {{ $locale }}-form @if($key == 0) d-block @endif">
                                                    <div class="form-group">
                                                        <label class="required" for="{{ $locale }}_name">{{ trans('Page title') }} ({{ \Illuminate\Support\Str::upper($locale) }})</label>
                                                        <input class="form-control @error($locale.'[name]') is-invalid @enderror" type="text" name="{{ $locale }}[name]" id="{{ $locale }}_name" value="{{ old($locale.'[name]') }}">

                                                        @error($locale.'[name]')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span>
                                                        @enderror

                                                    </div>
                                                </div>
                                            @endforeach
```

Controller

```
RuleFactory::make([
            '%name%' => 'required|string',
        ]);

        // Page
        $pageTranslationData = [
            'en' => [
                'name' => $request->input('en')['name']
            ],
            'ru' => [
                'name' => $request->input('ru')['name']
            ],
            'hy' => [
                'name' => $request->input('hy')['name']
            ],
            'alias' => $request->input('alias'),
            'parent_id' => $request->input('parent_id'),
            'sort_order' => $request->input('sort_order'),
        ];

        $resource = Page::create($pageTranslationData);

return redirect()->route('admin.page.edit', $resource->id);
```

**Comment by Gummibeer** [comment]
What's "not working"? Do you get an exception? A validation error? Does data pass that shouldn't? Or what happens?

You should also be able to use `Page::create($request->validated())` instead of all the single inputs and should also use a FormRequest.

Do you only call `RuleFactory::make()` or do you pass the result to a validator as rules array?
I have updated the example code https://docs.astrotomic.info/laravel-translatable/package/validation-rule-factory

**Comment by ciamarro** [comment]
have you tried the following?  (Remove the **'[]'** and add **'.'**)

    @error($locale.'.name')
    <span class="invalid-feedback" role="alert">
    	<strong>{{ $message }}</strong>
    </span>
    @enderror`

**Comment by ArtMin96** [comment]
Thank you guys. Now it's working well. Amazing support!
