### ISSUE TITLE
detect accept-language automatically

### ISSUE THREAD

**Issue by Marmahan** [Astrotomic/laravel-translatable#188]
Hi, First I want to thank you for the nice library.
I used to use spatie/laravel-translatable to handle translations of my models and now i moved to Astrotomic/laravel-translatable Everything works fine except that Astrotomic/laravel-translatable  doesn't detect accept-language automatically. In the past, I was able to specify which translation i want to get by setting accept-language to the required translation so if i want to get english translation i would set accept-language: en and the package would return the results in that language. Now this doesn't work, the package now returns only the first translation available. How can i make it detect accept-language automatically?

Thanks

**Comment by Gummibeer** [comment]
Hey,

I'm sorry but I couldn't find any code in the [spatie/laravel-translatable](https://github.com/spatie/laravel-translatable) package that handles the `accept-language` header!? 🤔

But to get to your current problem:
my recommendation would be to extend the `` class and rebind it to the service container.
You should override the `Locales::current()` method.
https://github.com/Astrotomic/laravel-translatable/blob/f36ddecd16616a35476f38846bf41c9597b56cdb/src/Translatable/Locales.php#L46-L49

And add your logic that parses and returns the `accept-language` locale.

**Comment by Marmahan** [comment]
Thank you for your answer. It is a bit difficult to do as to get the `accept-language` I need to do something like : `$request->server('HTTP_ACCEPT_LANGUAGE')` and I'm not sure how to pass the request to the `current` method. What do you think?

**Comment by Gummibeer** [comment]
You have two ways:
add the `Illuminate\Http\Request` to the `Locales::__construct()` as this is called with dependency injection. Or use helpers like `request()` or `Illuminate\Support\Facades\Request::instance()`.
All of them will work - it depends a bit on your personal preferences/rules and so on. The easiest will be the global helper function - but it's also the least "good" (OOP, DIC ...) way. But as you probably already use `config()`, `app()`, `response()` and other helpers why stop it!? 😉

But something else - you should use `$request->header('Accept-Language')` instead of `server()`.


Here's a little snippet from my `sparkling-water` Laravel(7) skeleton `Localize` middleware that could help you:
```php
    $this->parse(Arr::wrap($request->header('Accept-Language')));

    protected function parse(array $acceptLanguage): array
    {
        preg_match_all('/([a-z]{1,8}(-[a-z]{1,8})?)\s*(;\s*q\s*=\s*(1|0\.[0-9]+))?/i', Arr::first($acceptLanguage), $matches);

        if (empty($matches[1])) {
            return [];
        }

        /** @var array<string, string> $locales */
        $locales = array_combine($matches[1], $matches[4]) ?: [];

        foreach ($locales as $locale => $quality) {
            if ($quality === '') {
                $locales[$locale] = 1;
            }

            if (Str::contains($locale, '-')) {
                $lang = Str::before($locale, '-');

                $locales[$lang] ??= 0;
            }
        }

        arsort($locales, SORT_NUMERIC);

        return array_map('floatval', $locales);
    }
```

This will parse the `Accept-Language` header, add possibly missing language locales if there's only a country based one and sorts all of them by _quality_/preference.

After this you can use the result array with whatever logic you want - like always use the first (highest quality) or use them in a fallback detection loop (v12 #129 will helper here) or whatever you want. 😉

**Comment by Marmahan** [comment]
Perfect. Thank you for your reply. This is what i did so far:

`

use Astrotomic\Translatable\Locales;
use Astrotomic\Translatable\Translatable;
use Illuminate\Http\Request;



class CustomLocales extends Locales
{

    public Request $localRequest;


    public function current(): string
    {
        if(request()->server('HTTP_ACCEPT_LANGUAGE')){
            $this->translator->setLocale(request()->server('HTTP_ACCEPT_LANGUAGE'));
            return $this->translator->getLocale();
        }
        else
            return $this->config->get('translatable.locale') ?: $this->translator->getLocale();
    }

}
`
Do you think it is correct? 

Also how would Laravel now know to use this method over the original one? should i register it in serviceprovider (create my own...etc)?

**Comment by Gummibeer** [comment]
This should work if you want to solve it in the packages locale helper class - if you only need the locale there.

```php
use Astrotomic\Translatable\Locales;
use Astrotomic\Translatable\Translatable;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;

class CustomLocales extends Locales
{
    public function current(): string
    {
        if (request()->hasHeader('Accept-Language')) {
            return Arr::first($this->parseAcceptLanguageHeader(Arr::wrap(request()->header('Accept-Language'))));
        }

        return parent::current();
    }

    protected function parseAcceptLanguageHeader(array $acceptLanguage): array
    {
        preg_match_all('/([a-z]{1,8}(-[a-z]{1,8})?)\s*(;\s*q\s*=\s*(1|0\.[0-9]+))?/i', Arr::first($acceptLanguage), $matches);

        if (empty($matches[1])) {
            return [];
        }

        /** @var array<string, string> $locales */
        $locales = array_combine($matches[1], $matches[4]) ?: [];

        foreach ($locales as $locale => $quality) {
            if ($quality === '') {
                $locales[$locale] = 1;
            }

            if (Str::contains($locale, '-')) {
                $lang = Str::before($locale, '-');

                $locales[$lang] ??= 0;
            }
        }

        arsort($locales, SORT_NUMERIC);

        return array_map('floatval', $locales);
    }
}
```

What you've done should be done in a middleware like this:

```php
namespace App\Http\Middleware;

use Astrotomic\Translatable\Locales;
use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;

class Localize
{
    /**
     * @param Request $request
     * @param Closure $next
     *
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        foreach ($this->parse(Arr::wrap($request->header('Accept-Language'))) as $locale => $quality) {
            if ($this->setLocale($locale)) {
                break;
            }
        }

        return $next($request);
    }

    protected function setLocale(?string $locale): bool
    {
        if (app(Locales::class)->has($locale)) {
            app()->setLocale($locale);

            return true;
        }

        return false;
    }

    /**
     * @param string[] $acceptLanguage
     *
     * @return array<string, float>
     */
    protected function parse(array $acceptLanguage): array
    {
        preg_match_all('/([a-z]{1,8}(-[a-z]{1,8})?)\s*(;\s*q\s*=\s*(1|0\.[0-9]+))?/i', Arr::first($acceptLanguage), $matches);

        if (empty($matches[1])) {
            return [];
        }

        /** @var array<string, string> $locales */
        $locales = array_combine($matches[1], $matches[4]) ?: [];

        foreach ($locales as $locale => $quality) {
            if ($quality === '') {
                $locales[$locale] = 1;
            }

            if (Str::contains($locale, '-')) {
                $lang = Str::before($locale, '-');

                $locales[$lang] ??= 0;
            }
        }

        arsort($locales, SORT_NUMERIC);

        return array_map('floatval', $locales);
    }
}
```

Which I highly recommend if you want to use the same locale all over the app/request (translator, config, carbon, this package and so on).
This middleware is fully tested and defines the first in app available/configured locale from the header as the current one.

**Comment by Marmahan** [comment]
Thank you. This is great. I'm not sure about using a middleware for it as i only want to set the local language for each API call. for example, Say i'm requesting a post and i want the post to be in Spanish instead of English. I would then set accept-language in the header of my request to `es` and the API should return the post where translated attributes are in Spanish. so it is API-based thing.

**Comment by Gummibeer** [comment]
Use a route middleware and assign it only to your routes that should be localized. Or the group of routes. 😉
Middlewares are super powerful and flexible.

**Comment by Marmahan** [comment]
Oh yeah that's a good point actually. Thanks :)

**Comment by Marmahan** [comment]
One last thing though, `Localize` middleware should be started before `SubstituteBindings` , right? Other wise the instance will be resolved in the default language and then language will be changed.

**Comment by Gummibeer** [comment]
It's not important except you load the translations on model retrieve. If not the translations are loaded the moment you access `$model->translations` the first time or an translated attribute. Even then the locale isn't cached. So you could change the locale even mid request.
So the priority/order is only important if you use the app locale or a translated attribute in another language. Or if you use the translated attribute to resolve your model binding. For example if you use translated slugs.

**Comment by Marmahan** [comment]
I'm a bit confused about it. Isn't the default language translation fetched when the model is resolved with model binding? so in this case if the API request want the attributes in a different language then the middleware should be triggered before the model binding. Or do i understand it wrong?

**Comment by Gummibeer** [comment]
By default no translation is fetched until it's used.

**Comment by Marmahan** [comment]
Could you elaborate on this please?

**Comment by Gummibeer** [comment]
https://github.com/Astrotomic/laravel-translatable/blob/master/src/Translatable/Translatable.php

We only listen for `saved` and `deleting` but not for `resolved`. So there's simply no code that could load the translations when the model is resolved from DB.

All the logic happens for example in the attribute getter which gets the current translation from the `translations` relationship. 
https://github.com/Astrotomic/laravel-translatable/blob/f36ddecd16616a35476f38846bf41c9597b56cdb/src/Translatable/Translatable.php#L140-L162

**Comment by Marmahan** [comment]
I see. Thank you very much. Solved :)
