### ISSUE TITLE
Boolean translated attribute not working correctly

### ISSUE THREAD

**Issue by adam-riha** [Astrotomic/laravel-translatable#194]
**Describe the bug**
Boolean translated attribute not working correctly. 
Cast attribute to boolean in Model will not help. 

**To Reproduce**
Boolean column in **translations** table.
           
`$table->boolean('disabled')->default(false);
`

Fallback locale is `cs`.

#### Not correct:

Not correct if column value of fallback locale is true.

![not-correct](https://user-images.githubusercontent.com/22528181/97449344-d904e280-1931-11eb-8d93-5c696c26f336.png)

#### Correct:

Correct if column value of fallback locale is false.

![correct](https://user-images.githubusercontent.com/22528181/97449350-dacea600-1931-11eb-878a-56bc247fcea8.png)

#### Problem:

The problem is method `isEmptyTranslatableAttribute()`, used in `getAttributeOrFallback()` (trait Translatable).

https://github.com/Astrotomic/laravel-translatable/blob/69e8f625fe788fb45dffebb21d6f4c5a4949ba76/src/Translatable/Translatable.php#L340-L343

### Solution:

Add **not strict** comparison to zero.

```
protected function isEmptyTranslatableAttribute(string $key, $value): bool
{
    if ($value == 0) {
        return false;
    }

    return empty($value);
}
```

![fix](https://user-images.githubusercontent.com/22528181/97451412-0488cc80-1934-11eb-82c8-670abe89c1f2.png)

----

### Note:

Yes you can override method `isEmptyTranslatableAttribute()` in Model for custom column logic,
but **it would be preferable to have this boolean problem solved globally**.

Override example in `TranslatableTest.php::numeric_translated_attribute()`

https://github.com/Astrotomic/laravel-translatable/blob/69e8f625fe788fb45dffebb21d6f4c5a4949ba76/tests/TranslatableTest.php#L771-L783

**Versions (please complete the following information)**
- PHP: 7.3 | 7.4
- Database: mysql  Ver 8.0.19
- Laravel: **7**.28.4
- Package: 11.9.0

**Comment by Gummibeer** [comment]
Hey,
the `isEmptyTranslatableAttribute()` method was added to allow you to check whatever you need.
The `0` check will fail for translated into/float. So you are able and free to adjust it to whatever you want/need.
As there's no easy/good way to handle all possible cases and bools/ints/floats aren't this common to be translated and you are capable to adjust the logic to whatever you want.
