### ISSUE TITLE
How can I mock the insertion from Feature test?

### ISSUE THREAD

**Issue by pratamatama** [Astrotomic/laravel-translatable#199]
Instead of your current
```php
return $rules = [
    'translations.%name%' => 'required|string',
];
```
you just do
```php
return RuleFactory::make([
    'translations.%name%' => 'required|string',
]);
```
It will still return an array but will parse it and replace the placeholders.

_Originally posted by @Gummibeer in https://github.com/Astrotomic/laravel-translatable/issues/69#issuecomment-536593105_

**Comment by pratamatama** [comment]
I can't make it work to test the store endpoint with my current test setup. How can I mock it?

Already followed like mentioned above but the `FormRequest` aren't detecting the given `name` when I `dd($request->validated())` on the controller. 

`Test\Feature\LoanCategoryStoreTest.php`
```php
public function testShouldBeAccessibleByFinanceEmployee()
{
    $company = Company::factory()->hasEmployees(1)->createOne();
    $user = $company->employees->first()->syncRoles([
        $this->roleEmployee,
        $this->roleFinance,
    ]);

    $state['company_id'] = $company->id;
    $state['user_id'] = $user->id;
    $state['name:en'] = 'Oh yeah im handsome';

    $category = LoanCategory::factory()->state($state)
        ->makeOne()
        ->toArray();

    $this->actingAs($user, 'api')
        ->postJson(route('loanCategories.store'), $category)
        ->assertCreated()
        ->assertJsonFragment($category);
}
```

`Requests\LoanCategoryRequest.php`
```php
class LoanCategoryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    protected function uniquePerCompany()
    {
        return Rule::unique('loan_categories')
            ->ignore($this->id, 'id')
            ->where('company_id', $this->company_id);
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return RuleFactory::make([
            '%name%' => [
                'sometimes',
                'required',
                'string',
                $this->uniquePerCompany(),
            ],
        ]);
    }
}
```

`LoanCategoryController.php`
```php
/**
 * Store a newly created resource in storage.
 *
 * @param  \App\Http\Requests\LoanCategoryRequest  $request
 * @return \Illuminate\Http\Response
 */
public function store(LoanCategoryRequest $request)
{
    dd($request->validated());
    $category = $this->model->register($request->validated());
    return response()->json($category, 201);
}
```

**Comment by pratamatama** [comment]
Ah.. I fixed it. Had to use `translation.` prefix. I thought that was optional... Silly me.. Also, I also had to change
`$request->validated()` to `$request->all()` to make it works.

Sorry for this problem.

**Comment by Gummibeer** [comment]
Hey,
the `translation.` prefix should be optional and `$request->all()` shouldn't be required isn't recommended as it's unsecure.

Could you adjust your code a bit and check/post the result. It's about the `rules()` method and only for debugging.
* Revert to what you've posted in the issue
* Assign the `RuleFactory::make()` result to `$rules` before returning
* Put `dd($rules, $this->input());` between the `$rules` definition and return

This way we can compare the rules and the data the request receives and if they don't match.

**Comment by pratamatama** [comment]
Hi @Gummibeer , thank you for your response. Yes, I found that `$request->all()` are bypassing the validation and took all provided parameters on the fly. Fortunately, It breaks the security test so I fixed it already.

That also my mistake stating that `translations.` prefix was mandatory. I knew this by doing `dd($request->rules())` just like you mention above and do experiment with that by removing and re-adding the translations prefix.

However tho, I still can't use Factory for my test because `name:en` are always converted to this structure:

```php
[
  server_generated: false
  translations: [
      en: [
          name: "Oh yeah im handsome"
      ]
  ]
]
```

Because of that, the 'name:en' parameter is never exists so it doesn't get validated. Fixed by replacing the factory to an ordinary-hardcoded values like this

```php
$category = [
  'name:en' => 'Oh yeah im handsome'
];
```

This way, I can confirm the validation works as expected. But still, I feel a bit odd about why I can't use factory for this.

**Comment by Gummibeer** [comment]
Ah, now I see what's going on. You use the model factory and the data returned by model to array transformation as request data.

Let me explain a bit what's going on.

You insert `name:en` into the model. The package trait logic maps it into the english translation model. After the model is transformed to array which returns all non-hidden attributes and does the same for all loaded relationships - in this case the `translations` one. That's why you send `translations.name.en` to the controller instead of the `name:en` you've originally entered.

**Comment by pratamatama** [comment]
I see.. So that's the reason I can't use factory for this.. Thanks for the explanation.

One more question please, do you have any plan to add support for unique validation on Rule factory? I found it a bit difficult to achieve and I ended up adding new field on the translation table like.. 

```php
// LoanCategory.php
protected $translatedAttributes = [
    'athor_company_id',
    'name',
];

protected $fillable = [
    'author_id',
    'company_id',
];

// LoanCategoryTranslation.php
protected $fillable = [
    'author_company_id',
    'name',
];
```

To achieve that `uniquePerCompany()` rule I created above. Having `company_id` on both model seems kinda weird. It also interfering with the relationship when I remove the `author_` prefix.

**Comment by Gummibeer** [comment]
Could you please open a new issue as it's another topic and describe which problem you try to solve and what the package could provide to make it easier!?

**Comment by pratamatama** [comment]
Apologize for asking that question, thanks for the help anyways, really appreciate it..

**Comment by Gummibeer** [comment]
Hey, don't worry it's only to keep the issues clean and structured. 😊
