### ISSUE TITLE
Is it possible to use a custom string primary key in the model table instead of ID ?

### ISSUE THREAD

**Issue by fabien-lopes** [Astrotomic/laravel-translatable#201]
Hello,

Is it possible to use a custom string primary key in the model table instead of ID ?
Please find my source code below :

```
Schema::create('people_statuses', function (Blueprint $table) {
            $table->string('code');
            $table->timestamps();

            $table->primary('code');
        });
```

```
Schema::create('people_status_translations', function (Blueprint $table) {
            $table->id();
            $table->string('status_code');
            $table->string('locale')->index();
            $table->string('name');
            $table->string('description')->nullable();
            $table->timestamps();

            $table->unique(['status_code', 'locale']);
            $table->foreign('status_code')->references('code')->on('people_statuses')->cascadeOnDelete();
        });
```

Many thanks for your help

**Comment by fabien-lopes** [comment]
Hello @Gummibeer,

Can you help me on this topic please ?
I'm stuck.

Many thanks for your help

**Comment by ciamarro** [comment]
Have you tried setting public $translationForeignKey; ?

**Comment by fabien-lopes** [comment]
Hello @ciamarro, I tried but without success :(

**Comment by fabien-lopes** [comment]
Hello @Gummibeer ,

Can you help me on this topic please ?
I'm stuck.

Many thanks for your help

**Comment by fabien-lopes** [comment]
Ok! I found the solution.
Just set the following variables in your model :

``
public $primaryKey = 'code';'
'public $keyType = 'string';'
    public $incrementing = false;
``

Thanks
