### ISSUE TITLE
How can I iterate through translation attributes of model in a view?

### ISSUE THREAD

**Issue by ekcltfrm** [Astrotomic/laravel-translatable#202]
Hello all, 
I am trying to automate my form creation for translation entering. I need to iterate through the translated attributes of my model in my view. How can i get access to that?

`$model->translationAttributes` ,  `$model->gettranslationAttributes` both returns null.

**Comment by Gummibeer** [comment]
Hey,
the `$translatedAttributes` property is protected and there's no method to get it. So the easiest would be to add your own method that returns `$this->translatedAttributes`.
