### ISSUE TITLE
Simple access to localized attribute doesn't work, only with passing locale after it

### ISSUE THREAD

**Issue by Macartini** [Astrotomic/laravel-translatable#203]
Hi guys!
I checked current app locale before getting the data, it's ok, but when I try to get title/description/story by simple $page->title, it always return base app locale. If I pass the locale after attribute - it returns locale that I need. Ask for help.
**Page Container**
![Снимок экрана от 2021-01-12 11-01-19](https://user-images.githubusercontent.com/77324079/104293193-6c2bce00-54c6-11eb-89c9-a8d55488ca8e.png)
**Show page blade file**
![Снимок экрана от 2021-01-12 11-09-10](https://user-images.githubusercontent.com/77324079/104293389-9ed5c680-54c6-11eb-9913-37cae195c9ec.png)

**Comment by Gummibeer** [comment]
Hey,
have you defined the `locale` config key in the package config?
https://github.com/Astrotomic/laravel-translatable/blob/d853a3c34be42941dc83c5cddd9e1e98c71abae1/src/config/translatable.php#L34-L46
If so, set it to `null`. Otherwise this will always be used instead of the app locale.

**Comment by Macartini** [comment]
You are right! Set it to null, clear config and cache fixed my problem. Thank you so much!
