### ISSUE TITLE
App::setLocale does't work.

### ISSUE THREAD

**Issue by larvldeltacoding** [Astrotomic/laravel-translatable#205]
I'm using 11.9 version of laravel-translatable, laravel 5.8. and php 7.4

I want to use this example but it does't work: 
```
App::setLocale('de');
echo $post->title; // Mein erster Post
```
if I do `$post->translate('de')->title` than it works.

Do you have any idea why it is not working for me with only `echo $post->title`?

**Comment by AlbertoSinigaglia** [comment]
Same

**Comment by AlbertoSinigaglia** [comment]
EDIT:  
I solved removing this value:
```
/*
    |--------------------------------------------------------------------------
    | Default locale
    |--------------------------------------------------------------------------
    |
    | As a default locale, Translatable takes the locale of Laravel's
    | translator. If for some reason you want to override this,
    | you can specify what default should be used here.
    | If you set a value here it will only use the current config value
    | and never fallback to the translator one.
    |
    */
    'locale' => null, // previously was set to a language
```

Check this issue https://github.com/Astrotomic/laravel-translatable/issues/148

**Comment by larvldeltacoding** [comment]
Thank you, works as expected! It would be nice to know why it has to be null... hope somebody from contributors will explain it.

**Comment by AlbertoSinigaglia** [comment]
@larvldeltacoding you're welcome... idk

**Comment by Gummibeer** [comment]
Hey @larvldeltacoding ,
the packages `locale` config is if you want to manage the used locale totally separated from the app locale.
It's also described like this in the config description:

> If you set a value here it will only use the current config value and never fallback to the translator one.
