### ISSUE TITLE
Unable to export translatable config file

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [Astrotomic/laravel-translatable#206]
when i try to run
```
php artisan vendor:publish ‐‐tag=translatable
```

i get
```
No arguments expected for "vendor:publish" command, got "‐‐tag=translatable".  
```

I'm using Laravel 7.30.4

**Comment by Gummibeer** [comment]
Do you use Lumen instead of Laravel? As the Laravel `vendor:publish` command definitely works with the provided example code in documentation.

**Comment by AlbertoSinigaglia** [comment]
@Gummibeer nope, i'm using Laravel 7.X

**Comment by Gummibeer** [comment]
Could you post your `composer.json` file? Could it be that you've customized / overridden the default `vendor:publish` command? 🤔
<img width="915" alt="Bildschirmfoto 2021-02-17 um 21 46 17" src="https://user-images.githubusercontent.com/6187884/108265950-c70db080-7169-11eb-813a-5297469f8c72.png">
