### ISSUE TITLE
Undefined property: App\Category::$translatedAttributes

### ISSUE THREAD

**Issue by acwstudio** [Astrotomic/laravel-translatable#21]
**Describe the bug**
I have one to many relations Category to Post. Post::with('category')->get() causes the error
Undefined property: App\Category::$translatedAttributes

**Screenshots**
![error](https://user-images.githubusercontent.com/47781895/61190454-2578d000-a6a5-11e9-854e-abddca7dd50b.png)

**Comment by Gummibeer** [comment]
And does your category model use the `Translatable` trait?
If so you should define this property. If not I will need some more information and code about the category model.

**Comment by acwstudio** [comment]
I apologize for the trouble. I had typo I am fine now. Thank you very much for your job!
