### ISSUE TITLE
Unable to publish the package

### ISSUE THREAD

**Issue by bloominthedark** [Astrotomic/laravel-translatable#210]
Hi Tom Wiskowki and Astrotomic team.

I had a problem with the installation package.

I'm following the guide in Gitbook, after run cli : 'composer require astrotomic/laravel-translatable'. I can't publish the package with cli : 'php artisan vendor:publish --tag=translatable'.
The terminal return 'Unable to locate publishable resources.'
Then I check artisan vendor:publish,  I don't see this package provider in provider class and tag list, screenshot is attached below.
Please can tell me if I miss something in the installation step. After investigating, I think this package can help me solve localization in my project, so I really want to use this package as a solution.
Maybe the tag or provider name has been changed in an updated and that has not been updated in the document.
I'm using Laravel 8 and PHP 7.4, Composer 1.0 with the latest version of the package.

![Screen Shot 2021-03-10 at 14 29 18](https://user-images.githubusercontent.com/71001891/110592535-00f03680-81ad-11eb-805c-e14aa5302bfe.png).

**Comment by bloominthedark** [comment]
Sorry for this inconvenience.

I'm not sure why I got this error. But actually, the problem not came from your package. I try everything but it still not work.
Then I try to install another package, and... still facing the same problem. So I realized that the problem was from the local environment.

After all, I run "artisan config:cache" and IT'S WORKED.

It's so strange before run the config:cache,  the provider, and tag did not appear in the publishable list.

I will close this request and please mark it with a Question label, maybe it can help someone facing the same problem as me.

Once again, thanks if you took a look at this request.

**Comment by Gummibeer** [comment]
Hey, never cache in local environment.
You should run `artisan config:clear`.
