### ISSUE TITLE
how to get array for all translation with model? example: all()->getTranslationsArray()

### ISSUE THREAD

**Issue by nekooee** [Astrotomic/laravel-translatable#218]
how to get array for all translation with model? example: all()->getTranslationsArray()

I need to get a translation for my post model in the array.  
like this:
```
{
    "id": 1,
    "slug": "subject-1",
    "title": "subject 1",
    "content": "content 1",
    "translations": [
        {
		"en":[
            "title": "subject 1",           
            "content": "content 1"
			],
		"nl":[
            "title": "onderwerp 1",           
            "content": "inhoud 1"
			],
        }       
    ]
},
{
    "id": 2,
    "slug": "subject-2",
    "title": "subject 2",
    "content": "content 2",
    "translations": [
        {
		"en":[
            "title": "subject 2",           
            "content": "content 2"
			],
		"nl":[
            "title": "onderwerp 2",           
            "content": "inhoud 2"
			],
        }       
    ]
}
```

please help me.

**Comment by elnurxf** [comment]
+1

**Comment by Gummibeer** [comment]
Totally depends on the way you are generating that response. In general `$model->translations` is a default Laravel relationship that contains alls translation models - so you can add them to your JSON response however you want. I recommend an eloquent API resource class.

**Comment by elnurxf** [comment]
Thank you for your response. The thing is that we want to translations will come with keyBy('locale')

**Comment by Gummibeer** [comment]
You can do this in your API resource. You get a collection of translation models - so a quick way would be something like:

```php
$model->translations->keyBy('locale')->map->only('title', 'content');
```

The code isn't tested but should show one way to do it - it's by far not the best/cleanest way to do, but should work. 😉

**Comment by elnurxf** [comment]
That's works if I set a separate variable, unfortunately translations attribute can't be overrided.

**Comment by Gummibeer** [comment]
It doesn't have to be overridden!?

Your full JSON would be something like:

```php
return response()->json([
    'id' => $model->id,
    'slug' => $model->slug,
    'translations' => $model->translations->keyBy('locale')->map->only('title', 'content'),
]);
```

**Comment by nekooee** [comment]
I used this method in the model before you answered. I do not know how optimal it is. Although it works properly:

```
public $translatedAttributes = ['title', 'content'];

 public function getTranslationArraysAttribute()
    {
        $title = $this->translations()->pluck('title', 'locale');
        $content = $this->translations()->pluck('content', 'locale');
        return ['title' => $title, 'content' => $content];
    }
```
