### ISSUE TITLE
how to translate all the rows at one time

### ISSUE THREAD

**Issue by MohammedYAmmar** [Astrotomic/laravel-translatable#22]
```php
$categories = Category::all();
```

I want it to return 
```json
{
    "success":true,
    "data":[
        {
            "id":21,
            "category_id":2,
            "locale":"en",
            "name":"cat1",
            "details":"detials1",
            "image":"image1"
        }
    ]
}
```

for all the rows not like this

```json
{
    "success":true,
    "data":[
        {
            "id":2,
            "created_at":null,
            "updated_at":null,
            "deleted_at":null,
            "name":"cat1",
            "translations":[
                {
                    "id":21,
                    "category_id":2,
                    "locale":"en",
                    "name":"cat1",
                    "details":"detials1",
                    "image":"image1"
                }
            ]
        }
    ]
}
```

with out translation object

**Comment by Gummibeer** [comment]
Hey,

you should hide the key via one of the described ways in the [laravel docs](https://laravel.com/docs/5.8/eloquent-serialization#hiding-attributes-from-json) like following:

```php
Category::all()->makeHidden('translations');
```

**Comment by MohammedYAmmar** [comment]
thanks it works
But Is there any way 
to shorten this code
categories = Category::all()->makeHidden('translations');
        $i=0;
        foreach ( $categories as $category) {
         $category->setDefaultLocale($request->header('lang'));
            $i++;
        }

**Comment by Gummibeer** [comment]
https://github.com/Astrotomic/laravel-translatable/blob/8ec38419ef538e1e973dace59503299462dfca05/src/Translatable/Locales.php#L46-L49

You can set the `translatable.locale` config or change the app locale. These will set the locale for all translation models for the current runtime.

**Comment by MohammedYAmmar** [comment]
i have  used this 

 App::setLocale($request->header('lang'));

but it's not work

**Comment by Gummibeer** [comment]
What means "not work"? What's in your `$request->header('lang')`? What does `app('translatable.locales')->current()` return? Do you call it before the category query (you have to do so) or after it?

**Comment by MohammedYAmmar** [comment]
it not translate to the locale i send from the header

**Comment by MohammedYAmmar** [comment]
and i have done this but it is a still in the return the  default locale in the config file

?php

namespace App\Http\Middleware;

use Closure;

class SetLocale
{
     /**
      * Handle an incoming request.
      *
      * @param  \Illuminate\Http\Request  $request
      * @param  \Closure  $next
      * @return mixed
      */
    public function handle($request, Closure $next)
    {
        \App::setLocale($request->header('lang'));
        return $next($request);
    }
}

**Comment by Gummibeer** [comment]
If you've set a locale in config `translatable.locale` this won't be overridden. But you don't have to set it. It's just if you want to handle this packages locale separated from the app. In this case you can use `config('translatable.locale', $request->header('lang'))` to change it.

**Comment by MohammedYAmmar** [comment]
thank you so much it work now
