### ISSUE TITLE
How to use join while translation?

### ISSUE THREAD

**Issue by mshukurlu** [Astrotomic/laravel-translatable#220]
Hi friends!,

I want to use join when script getting the translations.

Here I want to reduce sql queries , 

Please guide me if my way is true or wrong,
Please see my queries 
![Screenshot_4](https://user-images.githubusercontent.com/11161906/114856543-47623200-9df8-11eb-93eb-58478d762805.png)

Here I have two sql for per request, for example :

I want to make my queries like this :  

`SELECT * FROM categories INNER JOIN category_translations on category_translations.category_id = categories.id `

How can I do that?.

For your opinon may be this is usefull or not?.

Thanks in advance!

**Comment by ciamarro** [comment]
Are you  doing `Category::with('translations')->get()`

**Comment by ciamarro** [comment]
To answer your question though :
```
DB::table('categories')->join('category_translations', 'categories.id', '=', 'category_translations.category_id');
```

**Comment by mshukurlu** [comment]
> Are you doing `Category::with('translations')->get()`

Yes I have load translations but it also creating query for twice.

**Comment by mshukurlu** [comment]
> To answer your question though :
> 
> ```
> DB::table('categories')->join('category_translations', 'categories.id', '=', 'category_translations.category_id')->get();
> ```

I have eloquent relationships so that I dont want use Db facade and I want to keep codes more similar so I want to look for ways with package.

**Comment by ciamarro** [comment]
You can use Eloquent

**Comment by Gummibeer** [comment]
Hey,

I see two problems in your query log.
1) not eager loaded translations
2) building a category tree in infinite queries

```php
$categories = Category::with('translations', 'subcategories')->get();
```

Joins aren't that helpful most times as joins are one of the most complex things in queries and are a lot of times slower than two separated queries.

**Comment by mshukurlu** [comment]
Thank you friends!
@Gummibeer I am using eager loading for demonstrate purpose  I had disabled it.
If you prefer 2 different sql queries then I also will use it. Thanks!
