### ISSUE TITLE
Fallback is not being found 

### ISSUE THREAD

**Issue by KhurshidYakubov** [Astrotomic/laravel-translatable#225]
I have 4 locales.  And I want to loop through my locales from top to bottom until one existing is found or end of list reached.

> My **_app/config/translatable.php_** file context looks like this: 

```
'locales' => [
        'ru',
        'uz',
        'oz',
        'en',
    ],

'locale' => null,

'use_fallback' => true,

'use_property_fallback' => true,

'fallback_locale' => null,
```

> **_Controller:_**

```
$list_types = ListType::paginate(5);

return view('admin.list_types.index', compact('list_types'));
```

> And **_index.blade.php_**:

`<p>{{ $list_type->translateOrDefault()->title}}</p>`

In my opinion, I follwed all instructions which are mentioned in [documentation.](https://docs.astrotomic.info/laravel-translatable/package/fallback-locale) However, it is keeping to return only the first locale. **How can I deal with this ?**

**Comment by Gummibeer** [comment]
Hey,
And which translations exist and which one is returned?

**Comment by KhurshidYakubov** [comment]
Fristly, creation order in **store()** function is like oz, uz, ru (en for future usage), as you can see below:
```
 $data = [
            'slug' => $get_slug_element,
            'oz' => [
                'title' => $request->oz_title,
            ],
            'uz' => [
                'title' => $request->uz_title,
            ],
            'ru' => [
                'title' => $request->ru_title,
            ],
            'status' => $request->status,
            'creator_id' => $user->id ?? 1,
        ];

        $list_type = ListType::create($data);
```

Data was inserted only for **_'uz'_** . But it is returning **_'oz'_** (which means the first one from table).
