### ISSUE TITLE
have bug in create in seeds

### ISSUE THREAD

**Issue by vahidalvandi** [Astrotomic/laravel-translatable#226]
**Describe the bug**
hi , i have bellow code work fine but in seed retrun error

```
        \site\entities\category::create([
            'path' => 'site',
            'is_sys' => 1,
           'fa' => [
                'title' => 'وب سایت',
           ],
           'en' => [
              'title' => 'website',
           ]
       ]);
```

**Versions (please complete the following information)**
- PHP:  7.4
- Database: 5.7
- Laravel: 8.4
- Package: **11.9.1**

**Additional context**

****Exception**
   ErrorException 

  Array to string conversion**

**Stack Trace**

 **vendor/laravel/framework/src/Illuminate/Support/Str.php:524
    520▕ 
    521▕         $result = array_shift($segments);
    522▕ 
    523▕         foreach ($segments as $segment) {
  ➜ 524▕             $result .= (array_shift($replace) ?? $search).$segment;
    525▕         }
    526▕ 
    527▕         return $result;
    528▕     }

      +22 vendor frames 
  23  database/seeders/DatabaseSeeder.php:16
      Illuminate\Database\Seeder::call()

      +22 vendor frames 
  46  artisan:37**

**Comment by Gummibeer** [comment]
Hey,

Please add a full stack trace as the important lines are missing.

**Comment by LAGGOUNE-Walid** [comment]
I figured out a temporary solution , i have a Category Model and CategoryTranslation .
so i created a factory for Category and another one for CategoryTranslation.
```php
$categroy = Category::factory()->create();
$categoryTranslations = CategoryTranslation::factory()->count(2)->state(
         new Sequence(
            ["locale" => 'fr'],
            ["locale" => 'ar'],
         )
      )->for($categroy)->create();
```

```php
<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

class CategoryTranslationFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition() {
        return [
            "name" => $this->faker->word
        ];
    }
}

```

```php
<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

class CategoryFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            "cover" => "xyz.png",
            "order" => $this->faker->randomDigit,
            "color" => $this->faker->hexColor,
            "status" => 1
        ];
    }
}

```
