### ISSUE TITLE
v11.9.1 doesn't save atttributes on laravel 8

### ISSUE THREAD

**Issue by teodoriu** [Astrotomic/laravel-translatable#228]
**Describe the bug**
Attributes not saving.

**Versions (please complete the following information)**
- PHP: 7.4
- Database: mysql 5.7 
- Laravel: 8.44
- Package: 11.9.1

**Additional context**
v11.9.0 seems to work

**Comment by Gummibeer** [comment]
Details missing

**Comment by teodoriu** [comment]
It seems that it was from another package.
