### ISSUE TITLE
Problems with changing the attribute (value) of the current locale

### ISSUE THREAD

**Issue by Basti007** [Astrotomic/laravel-translatable#238]
Hey, I've encountered the issue that I cannot update the locale that is currently being used.
I think I've done something wrong but I'm not quite sure.

My code looks like this:
```
$this->category->fill([
    'name:de' => $this->nameGerman,
    'name:en' => $this->nameEnglish
]);
$this->category->save();
```
The variables contain the right values.
The english name is updated if I set my locale to german but then the german name is not updated.

I hope that someone can help me :)

**Comment by Gummibeer** [comment]
If the package is properly configured this code will 100% work and do what is expected.
So the issue lives in your configuration or the form request you are using.

**Comment by Basti007** [comment]
What could be misconfigured that this part won't work?
I've followed the installation in the docs and even with hardcoded values the value of the current locale won't change.

**Comment by ordago** [comment]
@Basti007 I had the same problem. Not ideal but as a workaround this would make it work.
```php
$this->category->unsetRelation('translation');
```
