### ISSUE TITLE
Laravel dispatch events

### ISSUE THREAD

**Issue by bajki** [Astrotomic/laravel-translatable#239]
Hi, I want to use model events and it dosen't fire updated event on changed translated field.

So if i have field is_active and i change it, model fires event, but if i change translated name field it dosen't fire it.

Can you help me?

**Comment by Gummibeer** [comment]
Hey, the event fires on the translation model. So you have to listen to these events.

**Comment by bajki** [comment]
So how to create this?

Lets say i have this?

protected $dispatchesEvents = [
    'created' => ProjectCreated::class,
    'updated' => ProjectUpdated::class,
    'deleted' => ProjectDeleted::class,
];

protected $fillable = [ 'is_active'];
protected $translatedAttributes = ['name', 'description'];

If i change name how to fire ProjectUpdated::class

**Comment by Gummibeer** [comment]
Hey,
you should add the `'updated' => ProjectUpdated::class,` to your `ProjectTranslation` model.
