### ISSUE TITLE
Always load translations by locale key

### ISSUE THREAD

**Issue by olivermbs** [Astrotomic/laravel-translatable#241]
Currently when eager loading the translations relationship on a model, the output is as follows:

```
 $airport = Airport::with('translations')->findOrFail($id);

[{
    "id": 1,
    "airport_id": 219,
    "locale": "de",
    "name": "Flughafen"
}, {
    "id": 2,
    "airport_id": 219,
    "locale": "it",
    "name": "Aeroporto"
}, {
    "id": 3,
    "airport_id": 219,
    "locale": "en",
    "name": "Airport"
}]
```

The format I would like to use is the one which is produced by getTranslationsArray(), which comes out like this:

```
$airport['translationsArray'] = $airport['translations']->attributesToArray();

{
    "de": {
        "name": "Flughafen"
    },
    "it": {
        "name": "Aeroporto"
    },
    "en": {
        "name": "Airport"
    }
}

```

As I'm using InertiaJS/Vue, the second format is a lot easier to use in the templates. Is there any way to revert to this by default, without having to manipulate the eloquent result each time?

Thanks!

**Comment by ordago** [comment]
```php
$category->getTranslationsArray()

[
    'ca' => [
        'name' => 'Anglès',
    ],
    'en' => [
        'name' => 'English',
    ],
    'es' => [
        'name' => 'Inglés',
    ],
];
```

https://docs.astrotomic.info/laravel-translatable/package/methods#gettranslationsarray
