### ISSUE TITLE
Scope translatedIn(?string $locale = null) returns the same value as Model::all()

### ISSUE THREAD

**Issue by Nurzzzone** [Astrotomic/laravel-translatable#245]
Tried both methods and gettings the same objects with all translations instead of given in scope arguments

```
dd(Post::all(), Post::translatedIn('en')->get());
```

**Comment by Nurzzzone** [comment]
+ expected getting object with one translation like 

```
Post::translatedIn('en')->first()->toArray();
```
```
[
    'id' => 1,
    'image' => 'example/path/to/image.jpg',
    'translations' => [
         [
              'id' => 1,
              'locale' => 'en'
              'title' => 'hello'
              'post_id' => 1
          ]
    ] 
]
```

but I'm getting

```
```
[
    'id' => 1,
    'image' => 'example/path/to/image.jpg',
    'translations' => [
         [
              'id' => 1,
              'locale' => 'en'
              'title' => 'hello'
              'post_id' => 1
          ],
         [
              'id' => 2,
              'locale' => 'fr'
              'title' => 'bonjour'
              'post_id' => 1
          ],
         [
              'id' => 3,
              'locale' => 'de'
              'title' => 'hallo'
              'post_id' => 1
          ]
    ] 
]
```
```

**Comment by Gummibeer** [comment]
> `Post::translatedIn('en')->get();`
> Returns all posts being translated in english
https://docs.astrotomic.info/laravel-translatable/package/scopes#translatedin-string-usdlocale-null

It's just a filter scope - it doesn't interact in any way with the translation logic itself.

Also `toArray()` is the worst way to do API responses - you should use explicit API Resources.
https://laravel.com/docs/8.x/eloquent-resources

**Comment by Nurzzzone** [comment]
@Gummibeer toArray is just for demonstration

**Comment by Gummibeer** [comment]
It doesn't demonstrate anything - as for sure the `translations` relationship is loaded and transformed to an array.

**Comment by Nurzzzone** [comment]
@Gummibeer so I cant get result as excepted?

**Comment by Gummibeer** [comment]
Use an API resource and transform your model and relations however you want. But you should possibly use `translation` (singular) or directly add the translated attributes to the resource.

`$post->title` will always return the translated title for the current locale.

**Comment by Nurzzzone** [comment]
@Gummibeer Okay, got it. i just thought i can use this scope without creating addional classes

**Comment by Gummibeer** [comment]
Like said the `translatedIn()` is a plain filter scope that will filter the posts to all posts with a translation in the given locale.
After the posts are retrieved the same translate logic is used as always.

**Comment by Gummibeer** [comment]
PS: please stop mentioning me all the time. I will receive a notification with a simple comment as well.
