### ISSUE TITLE
disableAutoloadTranslations not working for me

### ISSUE THREAD

**Issue by vahidalvandi** [Astrotomic/laravel-translatable#247]
hello , i need disable translate with bellow model but not work

```
page::disableAutoloadTranslations();

$rows = pageTranslation::search($request->q)
    ->constrain(
        page::join('site_page_translations', 'site_page.id', 'site_page_translations.page_id')
    )
    ->take(30)
    ->first();
```

**Comment by Gummibeer** [comment]
And I need proper issues to help.

What does not work, what do you exactly mean with "does not work", do you get an exception, unwanted behavior, ...

**Comment by vahidalvandi** [comment]
just work when i convert to toArray()
