### ISSUE TITLE
Support different validation rules for different locales

### ISSUE THREAD

**Issue by Eyad-Mohammed-Osama** [Astrotomic/laravel-translatable#248]
First of all, i would like to say thanks for the maintainer and contributors of this great package

Let's say i want to generate different validation rules for different locales using ```RuleFactory```

For example, i want to make the fields in Arabic required while leaving them optional for the English version 

Is this possible in the current time or not ?, how can i achieve this ?

**Comment by Gummibeer** [comment]
Hey,

with one rule factory it isn't.
But you could use multiple with a different set of locales and rules and merge the resulting Arrays.

Or you hardcode your additional locale and rule and use `array_merge_recursive()` to add the additional rule to the primary locale.

At the end you will have to add/merge your rules manually.

**Comment by Eyad-Mohammed-Osama** [comment]
@Gummibeer Sounds like a good idea
Thank you very much
