### ISSUE TITLE
Sort with translation value and without translation value

### ISSUE THREAD

**Issue by kastoras** [Astrotomic/laravel-translatable#25]
**Is your feature request related to a problem? Please describe.**
I am using scopeOrderByTranslation when i try to order some data that has translation. 
I also need to order data from the basic table. 
When i try to sort with an element that doesn't exists to translations table and is only exists in basic table i get an error because in scopeOrderByTranslation method, in file Scopes.php line:64, (->orderBy($translationTable.'.'.$translationField) it add the translation table before the element.

**Describe the solution you'd like**
I would like to be able to order values from basic & translation table

**Describe alternatives you've considered**
I have created one method that i have delete the prefix of sorted value and it seems to work fine for translated and basic model values. 
This is the method:
```
    public function scopeOrderByTranslationOrNot(Builder $query, string $translationField, string $sortMethod = 'asc')
    {
        $translationTable = $this->getTranslationsTable();
        $localeKey = $this->getLocaleKey();
        $table = $this->getTable();
        $keyName = $this->getKeyName();

        return $query
            ->join($translationTable, function (JoinClause $join) use ($translationTable, $localeKey, $table, $keyName) {
                $join
                    ->on($translationTable.'.'.$this->getTranslationRelationKey(), '=', $table.'.'.$keyName)
                    ->where($translationTable.'.'.$localeKey, $this->locale());
            })
            ->orderBy($translationField, $sortMethod)
            ->select($table.'.*')
            ->with('translations');
    }    
```

Do you think that this is an acceptable solution?

**Comment by Gummibeer** [comment]
@kastoras if I got you right you have a translated column with the same name (I will name it `headline`) in the table of your main model `Post` and also in the table of the translation model `PostTranslation`?
If so then this is the underlying design issue why you get this exception and problem. This package isn't designed to have the same column in two tables. This will also lead to problems with the setter & getter.
This issue already occurred several times in the old repo - like:
* https://github.com/dimsav/laravel-translatable/issues/397
* https://github.com/dimsav/laravel-translatable/issues/471
* https://github.com/dimsav/laravel-translatable/issues/537 

And this wasn't supported at any time and also won't be official be supported in the future. Every value of a column relates to a locale so it could put into the translation table.

**Comment by kastoras** [comment]
Hello @Gummibeer,

no i don't have the same column names. At models table i have company_addrss_tk column and in models translation table i don't have this column.

In details the tables are:
### Model Table
```
CREATE TABLE IF NOT EXISTS `bc_companies` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `company_addrss_tk` varchar(70) COLLATE utf8mb4_unicode_ci NOT NULL,
  .
  .
  PRIMARY KEY (`id`),
) ENGINE=InnoDB AUTO_INCREMENT=20001 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

```
### Model Translation Table
```
CREATE TABLE IF NOT EXISTS `bc_company_translations` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `company_id` bigint(20) unsigned NOT NULL,
  `locale` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `company_name` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `company_address_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `company_address_town` varchar(70) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `bc_company_translations_company_id_locale_unique` (`company_id`,`locale`),
  KEY `bc_company_translations_locale_index` (`locale`),
  CONSTRAINT `bc_company_translations_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `bc_companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=40099 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

When i try to sort with **company_addrss_tk** column(It's only in Model's table) the method add table name to this column (**`bc_company_translations`.`company_addrss_tk`**) which doesn't exists on translation table.

This is the SQL part that get't the error (this is the SQL print using scopeOrderByTranslation method):
```
select `bc_companies`.* from `bc_companies` 
	inner join `bc_company_translations` on `bc_company_translations`.`company_id` = `bc_companies`.`id` 
		and `bc_company_translations`.`locale` = el 
		where `bc_companies`.`company_sync_date` <>  
order by **`bc_company_translations`.`company_addrss_tk`** asc limit 20 offset 0
```
If in this SQL part,  `company_addrss_tk` was without  `bc_company_translations` or with prefix from the correct table `bc_companies` I woudn't have that error.

**Comment by Gummibeer** [comment]
OK, but why do you use the `orderByTranslation()` scope if you want to order by a normal model column? You could use the default `orderBy()` scope https://laravel.com/docs/5.8/queries#ordering-grouping-limit-and-offset

Or why do you want to use the same method/scope for two different order tasks?

**Comment by kastoras** [comment]
I am using this because i need to sort a data table with both translated and not translated values. 

Also I have filters and sort operations together for these values. I need to use where with translated value and order by non translated value so l pass the value i need to sort dynamically.

I'ts a bit complex search. 
When i use the method i have created, it works for all these scenarios so far.

**Comment by Gummibeer** [comment]
OK, I already thought so that you have something where you pass the query params from the frontend.

Because this is a very special case and the solution is kind of hacky I won't add this to the package itself.
Some thoughts:
except of passing the order column without table prefix you could use the `isTranslationAttribute()` method https://github.com/Astrotomic/laravel-translatable/blob/c304eddcc57f1f656c72216aa2f2ce0b2ac69473/src/Translatable/Translatable.php#L226-L229 to check if the column is translated or not and use the corresponding scope. So I would add a custom scope like following:

```php
public function scopeOrderByTranslationOrModel(Builder $query, string $column, string $sortMethod = 'asc')
{
    if((new static)->isTranslationAttribute($column)) {
        $query->orderByTranslation($column, $sortMethod);
    } else {
        $query->orderBy($column, $sortMethod);
    }
}
```

This scope is much simpler, has no code duplication and you don't have to adjust something if the logic of the original translation scope is changed.
Because it's also very easy to add new custom scopes (create a new trait which uses the package one) I won't add it to the package itself. But I hope that this helps you to accomplish your needs in your own app?

**Comment by kastoras** [comment]
Thanks for your suggestions, i have already used this approach and it goes more complicated at the end... 

I will try to use orderByTranslation with the modification i need to a Helper.

Thanks in advance.
