### ISSUE TITLE
Option to ignore checking null for SQL optimization

### ISSUE THREAD

**Issue by HuyPham55** [Astrotomic/laravel-translatable#255]
I have a translatable model declared as below, nothing extra-ordinary:
Slide.php
```php
public $translationForeignKey = 'slide_id';
public $translationModel = SlideTranslation::class;
public $translatedAttributes = ['content'];
```
SlideTranslation.php
```php
protected $table = 'slide_translations';
protected $fillable = ['content'];
public $timestamps = false;
```

When I want to retrieve translations for Slide model with a specific id, take 5 for example. This is the SQL statement that I observed: 
```php
$content = Slide::find(5)->content;
```

```sql
select * 
from `slide_translations` 
where `slide_translations`.`slide_id` = 5 
and `slide_translations`.`slide_id` is not null
```

It appears that the later part ( `slide_translations`.`slide_id` is not null` ) is un-neccessary. I wonder if there is an option that I'm missing to ignore the second condition, or the package needs a small improvement. Thanks for reading.

**Comment by Gummibeer** [comment]
Hey,
the query isn't made by us but Laravel itself.
https://github.com/laravel/framework/blob/fda820074cc888495c78c9a76e7fa98fa4980d79/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php#L75-L89
