### ISSUE TITLE
How To Update Model TimeStamps

### ISSUE THREAD

**Issue by boranbar** [Astrotomic/laravel-translatable#259]
Hello,

First of all, thank you for this great package.

I have a question about timestamps.

So let's assume we have posts and post_translations table.

According to the docs, there is no created_at and updated_at columns on translation table.

I realized that, if i update some record in post_translations table, my main posts table's updated_at column is not changing.

If one of the columns in my post_translations table is updated, I want the updated_at column of my main table to be also updated.

How can i achieve that?

Thanks for the help.

**Comment by boranbar** [comment]
**UPDATE**
Here is the solution;

In our PostTranslation model, all we have to do define a belongsTo relation and use Elequent touch.

```
protected $touches = ['post'];

public function post(): BelongsTo
    {
        return $this->belongsTo(Post::class);
    }
```

**Comment by ahbanavi** [comment]
@boranbar FYI, Your solution doesn't work if lazy loading is disabled.

![image](https://user-images.githubusercontent.com/39927312/231710239-80c5669a-987d-4dd0-a8a9-0d3fb3413868.png)
![image](https://user-images.githubusercontent.com/39927312/231710293-6a55138d-38fd-4d0a-9cd3-d889f88a306f.png)
