### ISSUE TITLE
Laravel 5.7 dimsav translatable to Laravel 8

### ISSUE THREAD

**Issue by tarturek** [Astrotomic/laravel-translatable#263]
I am using L 5.7 with dimsav/laravel-translatable

I want to update my project to Laavel 7 or 8 . What i need to do if i want to use laravel-translatable.

Thank you

**Comment by Gummibeer** [comment]
Hey, the most notable change was the namespace change.
Besides that nothing big changed - the changelog is complete, so you can walk through it.
