### ISSUE TITLE
how to select custom filed from translation table 

### ISSUE THREAD

**Issue by arbabi2010** [Astrotomic/laravel-translatable#264]
Hi , i want to select only title , slug from post_translations table and i won't select summary and other filed . how can i select specific column instead all fields .

**Comment by Dezmonter** [comment]
This is a big problem(We lose performance by selecting all translation fields(

**Comment by Gummibeer** [comment]
It's a full relational DB setup. In case you really care about that kind of performance you can go all in for a custom query - plain SQL or eloquent is up to you. But you are free to eagerly load the translations relationship or even the translation one with a callback and select only what you need.
But that's up to you and your business logic. In case you find an easy to add but still flexible solution for a scope you can post it here and we can check if it's PR worthy or not.

**Comment by Dezmonter** [comment]
Here is my solution to this issue...

```
 public function scopeWithTranslationOnly(Builder $query, array $translationFields)
  {
    array_push($translationFields, $this->getTranslationRelationKey(), 'locale');
  
    $query->with([
        'translations' => function (Relation $query) use ($translationFields) {
            return $query->select($translationFields)->where($this->getTranslationsTable().'.'.'language_id', LanguageFacade::getLanguage()->id);
        },
    ]);
 }
```

**Comment by Gummibeer** [comment]
#416
