### ISSUE TITLE
Updated Event In translated model 

### ISSUE THREAD

**Issue by fathirasid** [Astrotomic/laravel-translatable#268]
Thanks for this package .. 
I need to log translated model , I made a loggable trait which observe translated model events and logging it in database . 
But there is a problem ,When user making only update on ModelTranslation fields , the updated Event fire on only ModelTranslation , so I cannot log the main translated model . What can I do without logging ModelTranslation ?

**Comment by fathirasid** [comment]
We resolved this problem, when we make an update query to database, we update the timestamp of the main model like that code : 

```php
   $model->fill($request->validated());
   $model->updated_at = now();
   $model->save();
```
which updates the main model automatically, so it will fire update event.

**Comment by Gummibeer** [comment]
https://laravel.com/docs/9.x/eloquent-relationships#touching-parent-timestamps
