### ISSUE TITLE
Sort by translation using translatable along spatie/laravel-query-builder

### ISSUE THREAD

**Issue by bpuig** [Astrotomic/laravel-translatable#27]
Has anyone tried using translatable with [spatie/laravel-query-builder](https://github.com/spatie/laravel-query-builder) ? 
If so, how can I sort by translation fields?

Thanks

**Comment by Gummibeer** [comment]
I can't find anything in the docs about sorting by a join or scope.
So I would say you will have to tinker with it. But I will also check if I find a way.

**Comment by Gummibeer** [comment]
@bpuig you will have to create a custom sort class: https://github.com/spatie/laravel-query-builder/pull/91

**Comment by Gummibeer** [comment]
#25 could help you to write the sort class and handle translatable and normal attributes in it.

**Comment by bpuig** [comment]
Perfect! I'm glad that it seems possible, I'll give it a try and then write my results in case it's useful to someone

**Comment by bpuig** [comment]
Got it!
First on spatie's query builder add one or many custom sort:
```
use Spatie\QueryBuilder\Sort;

...

->allowedSorts(Sort::custom('name', BookSort::class, 'name', Sort::custom('description', BookSort::class, 'description')
```
Then create a class:
```
use Illuminate\Database\Eloquent\Builder;
use Spatie\QueryBuilder\Sorts\Sort;

class BookSort implements Sort
{
    public function __invoke(Builder $query, $descending, string $property) : Builder
    {
        return $query->OrderByTranslation($property, $descending ? 'desc' : 'asc');
    }
}
```
And voilà! It works.
