### ISSUE TITLE
How to get only translations of the current locale?

### ISSUE THREAD

**Issue by nunowar** [Astrotomic/laravel-translatable#270]
Hi.

I would like to get only translations of the current locale.

I use: `protected $with = ['translations'];` to eager load, but I would like to know if it's possible to get only the current locale translations.

Thanks.

**Comment by sdn1364** [comment]
Hi, I have the same problem. there are a lot of unnecessary models loaded in page

**Comment by Gummibeer** [comment]
https://github.com/Astrotomic/laravel-translatable/blob/6f2e3855836d46ab7ad3dabd269a400404f8b42c/src/Translatable/Traits/Relationship.php#L64-L69

This one should be reworked to a `hasOne()->ofMany()` relationship in the future - but it works.
