### ISSUE TITLE
route with translated post slug

### ISSUE THREAD

**Issue by IslamYCB** [Astrotomic/laravel-translatable#272]
Hello guys,

how do I get the post translated slug in route 
in my routes I'm using:
```php
Route::get('posts/{post:slug}', [PostController::class, 'show'])->name('post');
```

but of course if slug is translated this wouldn't work, so how do I refer for the translated slug in the route instead of {post:slug} since this doesn't work

**Comment by Gummibeer** [comment]
Hey,

this only works with a custom substitution middleware, like that one in the enum package: https://github.com/spatie/laravel-enum/blob/main/src/Http/Middleware/SubstituteEnumBindings.php

Or by resolving the slug in your controller using the `whereTranslation()` scope.
https://docs.astrotomic.info/laravel-translatable/package/scopes#where-translation

**Comment by MustafaMohammed99** [comment]
create empry model  PostTranslation

and in route use like this
Route::get('posts/{postTranslation:slug}', [PostController::class, 'show'])->name('post');

and in PostController show
    public function show(PostTranslation $post){}
