### ISSUE TITLE
Problem with use_property_fallback - returns null.

### ISSUE THREAD

**Issue by PitchRE** [Astrotomic/laravel-translatable#278]
As title; 

Config
```php

    'locales' => [
        'en_US',
        'ja_JP',
        'pl_PL'

    ],

  'locale' => null,
   'use_fallback' => true,
 'use_property_fallback' => true,
'fallback_locale' => 'en_US',
```

Code

```php


    app()->setLocale('en_US');
    $item = Item::factory()->create();

    app()->setLocale('ja_JP');

    $item->update(['ja_JP' => [
        'name' => Item::factory()->make()->name
    ]]);

    //// slug for ja_JP is always null;

    return $item->translate('ja_JP', true);
```
Output

```json
{
"locale": "ja_JP",
"name": "加納 裕太",
"item_id": 22,
"id": 43
}
```
I excepted 'slug' and 'description' property to not be null.

`$item->getTranslationsArray() outputs`

```json
{
"en_US": {
"name": "Jazlyn Kunze",
"description": "Minus eos et nulla quia sint vel vel eveniet. Enim dolor omnis quod quia quos nihil ipsum. Odio et cum quis praesentium ut et perferendis. Mollitia sint debitis at. Ut magnam quia dolorum qui.",
"slug": "jazlyn-kunze"
},
"ja_JP": {
"name": "小林 美加子",
"description": null,
"slug": null
}
}
```

What do I do incorrectly?

**Comment by Gummibeer** [comment]
`translate()` returns the translation model instance - which will be `ja_JP` as requested.
If you want to use the property fallback you should use `$item->slug` - these will use the property fallback as you request a specific model attribute.

**Comment by PitchRE** [comment]
Thank you for clarification. So I guess there is no way to make use of property fallback feature without changing locale globally in the app?

**Comment by Gummibeer** [comment]
You can also pass the locale as part of the attribute `$post->{'title:de'}`.
https://docs.astrotomic.info/laravel-translatable/usage/attributes
