### ISSUE TITLE
Translated columns sets to null values while using Query Builder

### ISSUE THREAD

**Issue by mshukurlu** [Astrotomic/laravel-translatable#28]
**Describe the bug**
I am making a Query with Joins . When I want to response translated columns in API they converting to null values.When I hide $translatedAttributes in the model everything works well. Or selecting the columns with an alias for example name as n it returns the value.
**To Reproduce**
My Database Schema
pages table:
  ```
  Schema::create('pages', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('slug');
            $table->integer('status');
             $table->string('type')->nullable();
            $table->timestamps();
        });

```
page_translations table:
```
   Schema::create('page_translations', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->bigInteger('page_id')->unsigned()->index();
            $table->foreign('page_id')->references('id')->on('pages')->onDelete('cascade');
            $table->string('locale');
            $table->string('name');
            $table->longText('text');
            $table->timestamps();
        });
```

My Page Model:

```
class Page extends Model
{
    use \Astrotomic\Translatable\Translatable;
    
    public $translatedAttributes = ['name','text'];
    protected  $fillable = ['slug','status'];

    public function page_meta()
    {
        return $this->hasMany('App\Models\Page\PageMeta');
    }

    public function getDocumentLinkAttribute()
    {
        return $this->page_meta()->first()->meta_value;
    }
}

```
PageTranslations model class
```

PageTranslation extends Model
{
   public $timestamps=false;

   protected $fillable = ['name','text','status'];
}
```

My codes :  

```
    protected  $pageModel;

    public function __construct(Page $page)
    {
        $this->pageModel = $page;
    }

    public function getApiWithType($type)
    {
        return $this->pageModel->leftJoin('page_translations','pages.id','=','page_translations.page_id')->where('page_translations.locale','az')->where('pages.type','page')->get();
    }
```

**Expected behavior**
I am making a Query with Joins. When I want to response translated columns in API they converting to null values.When I hide $translatedAttributes in the model everything works well. Or selecting the columns with an alias for example name as n it returns the true value.

**Versions**
- PHP: 7.2.11
- Database: Mysql
- Laravel: 5.8
- Package:

**Comment by Gummibeer** [comment]
Why do you want to join the translations instead of the default behavior? The trait is made to handle all the logic. By joining them your own you make the trait useless and it could create conflicts.
If you have disabled auto-loading you can use the `withTranslation()` scope.
https://docs.astrotomic.info/laravel-translatable/usage/scopes#withtranslation
https://github.com/Astrotomic/laravel-translatable/blob/8ec38419ef538e1e973dace59503299462dfca05/src/Translatable/Traits/Scopes.php#L109-L124

**Comment by mshukurlu** [comment]
@Gummibeer I need to use this like that, I don't need use even translation in this task, If it is possible to deactivate I intend to it in this action, I would use it. Anyway, any package should not affect to another workflow of the application. This is a bug.

**Comment by Gummibeer** [comment]
You are able to disable the translations on runtime for a specific model.
https://docs.astrotomic.info/laravel-translatable/usage/methods#static-disableautoloadtranslations
https://github.com/Astrotomic/laravel-translatable/blob/8ec38419ef538e1e973dace59503299462dfca05/src/Translatable/Translatable.php#L41-L44

I think that the problem relates to the `fill()`, `setAttribute()` and/or `getAttribute()` methods which have problems with the translated attribute from the join.

> Anyway, any package should not affect to another workflow of the application.

That is right as long as the workflow doesn't touch the package. The moment your custom workflow interferes the package you can't expect the package to work normal.
That's the contract if you use a package. Every package comes with an intended and official way. Everything besides this could work but don't have to. You can feel free to find a way which allows your code to work without removing an existing functionality and not too much changes.

**Comment by vahidalvandi** [comment]
hello , i need disable translate with bellow model but not work

         ```
   page::disableAutoloadTranslations();

            $rows = pageTranslation::search($request->q)->constrain(page::join('site_page_translations', 'site_page.id', 'site_page_translations.page_id'))->take(30)->first();

```
