### ISSUE TITLE
Translations aren't added automatically when mass update

### ISSUE THREAD

**Issue by qualishovt** [Astrotomic/laravel-translatable#280]
Hello, thank you for this package. I have an issue. Your documentation says this:

### Saving the request
Both ways are ready to save the translatable attributes to the model without any other modification.
```
public function update(Request $request, Post $post)
{
  $post->update($request->all());
}
```

[https://docs.astrotomic.info/laravel-translatable/usage/forms#saving-the-request](https://docs.astrotomic.info/laravel-translatable/usage/forms#saving-the-request)

However, translation fields aren't inserted or updated unless I call `translateOrNew($locale)` method. Can you help me with this?

**Comment by Gummibeer** [comment]
Have you configured the allowed locales? And what's your configuration at all and how does the request look like?
