### ISSUE TITLE
Additional Data in "translation" table.

### ISSUE THREAD

**Issue by buzzclue** [Astrotomic/laravel-translatable#30]
Is it possible to save some additional data in translate table?

```php
Route::get('demo', function() {
    $page = new App\Page();
    $page->post_type = 'page';
    $page->published = true;
    $page->save();

    foreach (['en', 'nl', 'fr', 'de'] as $locale) {
        $page->user_id = 12;
        $page->translateOrNew($locale)->slug = str_slug("Title {$locale}");
        $page->translateOrNew($locale)->title = "Title {$locale}";
        $page->translateOrNew($locale)->meta_title = "Title {$locale}";
        $page->translateOrNew($locale)->meta_description = "Title {$locale}";
        $page->translate_published = true;
    }
    $page->save();

    echo 'Created an article with some translations!';
});
```

I am trying to add an option to make translation **published or draft** and maybe some fields?

I tried creating protected **$fillable** object in "**PageTranslation**" modal. But it always try to save everything in **pages** table

**Comment by Gummibeer** [comment]
Hey,

you can add as much columns as you want. They just have to exist in the migration, be fillable in the translation model and listed in the `$translatedAttributes` property of the main model.

**Comment by buzzclue** [comment]
Thank you for your prompt response. I just realized that i will have to add:
`$page->translateOrNew($locale)->`
with value in order to reference it to translation table. Can you please tell me if this is the best way of doing it?

**Comment by Gummibeer** [comment]
Depends on your table structure, the reason for the relation and so on.
A relation between `page_translation` and `user` is only useful if you want to track the author of the specific translation. In this case I would rename it to `author_id`. 😉 
If you just want to keep track of the author of the original page the relation should be between `page` and `user` - I would also name it `author_id`.

Depending on the kind of content and reason to track the translation author it could be useful to put this relation in a pivot `n:m` table to also keep track on the users who update/fix/improve/complete a translation.
For things like this I also could recommend [spatie/laravel-activitylog](https://github.com/spatie/laravel-activitylog) to track the activities including a comment/reason why the translation was edited.

But these are all just blind-shots. If you tell me what's your goal I can help you better and more focused.

**Comment by Gummibeer** [comment]
PS: if you have a form where you list all translations or something like this you can use the overridden `fill()` method and sub-array syntax. https://docs.astrotomic.info/laravel-translatable/usage/forms

**Comment by buzzclue** [comment]
Content on this project is translated by users and that's why i have user_id as foreign key in translation table.
>  A relation between page_translation and user is only useful if you want to track the author of the specific translation. 

I already added user_id in pages, i realized it when i deleted one user and pages were not deleted.

Thanks i have renamed user_id 
> In this case I would rename it to author_id. 😉

I am already using that :)
> For things like this I also could recommend spatie/laravel-activitylog

**Comment by Gummibeer** [comment]
Ok, so is it solved? Or do you have any questions?

**Comment by buzzclue** [comment]
Thank you for your great work. 

One last question :) is this the best way of handling add/edit?

**Comment by Gummibeer** [comment]
To track I would use the activitylog. This will log what changed, who did and also a why as description. This way you can display a whole log and also something like https://de.ifixit.com/Anleitung/iMac+Intel+27-Inch+EMC+2309+und+2374+RAM+Abdeckung+austauschen/1629 where also the visitor can see who translated it.

The author relationship on the translation would only be useful if the original creator should have special rights like rejecting/approving updates.
For lists I would just read from the activity relationship.
