### ISSUE TITLE
Any package to support Nova 4

### ISSUE THREAD

**Issue by vbezruchkin** [Astrotomic/laravel-translatable#301]
Hi there, 

Thanks for your work, the package is super helpful! We've been using it for some projects for some years already. 

Anyhow, now it's time to upgrade to Nova 4, and looks like there is no package that would support the new version of Nova. Do you have any plans to make own plugin that would support Nova 4? 

Thanks a lot!

**Comment by Gummibeer** [comment]
No, as nova is a closed source proprietary monetized package. Feel free to create your own and open a PR to add it to the readme/docs.

In general it's also as easy as creating a new resource and link both by has many and belongs to fields. Everything more advanced would need custom Vue components.
