### ISSUE TITLE
How to fetch all Model objects which are translated to a specific language?

### ISSUE THREAD

**Issue by amirakbulut** [Astrotomic/laravel-translatable#31]
I'm using Twill CMS, which uses the previous version of this package to translate models. (dimsav/translatable), however it's read only.

I have a multilingual website with a blog page that shows all my posts. However, if a blog post isn't translated (yet) to the current locale of the visitor, it just shows an empty post card without any content.

So how do I fetch all Posts that are translated to the current locale? Let's say my current locale is Spanish, I'd like to only show posts that are translated in the spanish language.

**Comment by Gummibeer** [comment]
Hey,

the solution is the `translatedIn()` scope.
https://docs.astrotomic.info/laravel-translatable/package/scopes#translatedin-string-usdlocale-null

This scope also exists in the old package. So you can use it without changing any dependencies.

But it shouldn't be this hard to move to the new package. Which is highly recommended to stay up-to-date.

**Comment by amirakbulut** [comment]
Hi @Gummibeer 

Thanks for your reply. I actually tried this function before writing this issue, but it's not working for me.

I'm using `Post::translatedIn('en')->orderBy('id', 'desc')->where('published', 1)->paginate(6);` and it still shows me every single post item.

**Comment by Gummibeer** [comment]
Could you dump and post the executed query?
You can use
* https://github.com/barryvdh/laravel-debugbar
* https://github.com/laravel/telescope

to get the executed queries.
So far your code looks right. And is your app locale also `en` or could it be that you query all `en` posts but the trait translates to `de` (or any other locale).

**Comment by amirakbulut** [comment]
> Could you dump and post the executed query?
> You can use
> 
> * https://github.com/barryvdh/laravel-debugbar
> * https://github.com/laravel/telescope
> 
> to get the executed queries.
> So far your code looks right. And is your app locale also `en` or could it be that you query all `en` posts but the trait translates to `de` (or any other locale).

Yes it's:

````select * from `posts` where exists (select * from `post_translations` where `posts`.`id` = `post_translations`.`post_id` and `locale` = 'en' and `post_translations`.`deleted_at` is null) and `published` = 1 and `posts`.`deleted_at` is null order by `id` desc limit 6 offset 0````

**Comment by Gummibeer** [comment]
Ok, even the query looks 100% right. Just a question: is the `published` column part of the `posts` or `post_translations` table?

Because your query will definitely select all posts which have a translation in `en` which is not deleted and the post is published and also not deleted.

Could you dump `Locales::current()`? Atm it's the only reason I could imagine that you select all `en` posts but display another locale. 🤔

**Comment by amirakbulut** [comment]
> Ok, even the query looks 100% right. Just a question: is the `published` column part of the `posts` or `post_translations` table?
> 
> Because your query will definitely select all posts which have a translation in `en` which is not deleted and the post is published and also not deleted.
> 
> Could you dump `Locales::current()`? Atm it's the only reason I could imagine that you select all `en` posts but display another locale. 🤔

The `published` column is part of the `posts` table.

Regarding the following: 

> Atm it's the only reason I could imagine that you select all en posts but display another locale. 

It actually isn't displaying the post in another language, it's simply returning empty content because the specific Post object isn't translated to the current locale yet.

**Comment by ifox** [comment]
Hi guys, sorry for the trouble here. This issue is actually coming from the fact that Twill has an additional column in the translations tables to manage the publication status per language.

@Gummibeer we are about to release a new version that migrates Twill to this dependency! Thank you for your help.

**Comment by Gummibeer** [comment]
@ifox thanks for clarifying this! 😊
Feel free to write an issue if you need any help to migrate. I hope the new docs help to understand everything.

**Comment by amirakbulut** [comment]
> Hi guys, sorry for the trouble here. This issue is actually coming from the fact that Twill has an additional column in the translations tables to manage the publication status per language, and we provide our own scope [here](https://github.com/area17/twill/blob/6c757f924d9903cc187f719b0e7ea9cb755671dc/src/Models/Behaviors/HasTranslation.php#L16).
> 
> @Gummibeer we are about to release a new version that migrates Twill to this dependency! Thank you for your help.

Hi @ifox,

Thanks for clarifying this. However, I wasn't able to call this function directly from my model instance. How would I implement it within my current code:

`Post::orderBy('id', 'desc')->where('published', 1)->paginate(6);`

I really appriciate your help.

**Comment by Gummibeer** [comment]
@amirakbulut even if I don't use the package, this should do the trick if you use the linked trait.

```php
Post::withActiveTranslations($locale)->orderBy('id', 'desc')->where('published', 1)->paginate(6);
```
