### ISSUE TITLE
Transltable Slug Validation.

### ISSUE THREAD

**Issue by buzzclue** [Astrotomic/laravel-translatable#32]
How to do slugs validation? 

```php
//categories
Schema::create('categories', function (Blueprint $table) {
          $table->bigIncrements('id');
          $table->integer('order')->index('order')->default(0);
          $table->tinyInteger('status')->default(1);
          $table->tinyInteger('show_menu')->default(1);
          $table->integer('parent')->index('parent')->nullable();
          $table->timestamps();
});

//categories translations schema
Schema::create('category_translations', function (Blueprint $table) {
          $table->bigIncrements('id');
          $table->string('locale')->index();
          $table->unsignedBigInteger('category_id');
          $table->string('name', 100)->index('name');
          $table->string('slug', 100)->unique('slug')->index('slug');
          $table->unique(['category_id', 'locale']);
          $table->foreign('category_id')->references('id')->on('categories')->onDelete('cascade');
});
```
In my implementation we add content in single(en) language and users translate the content. Now with slugs, there is a possibility for some slugs to never get translated.

For example slug for category in English is **entertainment** and French slug is also **entertainment** and it can be both different for other categories.

**Comment by Gummibeer** [comment]
Hey,

I'm sorry but I don't get what's your question? Could you explain in more detail what you want to do and what doesn't work or you are unsure how to do?

**Comment by buzzclue** [comment]
i am trying to validate unique slug and the slug is unique with 2 columns.

```php
$table->unique(['slug', 'locale']);
````

make sense?

**Comment by Gummibeer** [comment]
**Adding Additional Where Clauses**
https://laravel.com/docs/5.8/validation#rule-unique

```php
'slug' => Rule::unique('category_translations')
    ->ignore($category->id, 'category_id')
    ->where(function ($query) use ($locale) {
        return $query->where('locale', $locale);
    })
```

It's not tested but this should do the trick. It will ignore the current translation and limits the pool where it has to be unique to all with the same locale.

**Comment by buzzclue** [comment]
Awesome! you are great.
