### ISSUE TITLE
SyncTranslations Method on Update

### ISSUE THREAD

**Issue by buzzclue** [Astrotomic/laravel-translatable#33]
Is there a method to Sync Translations on update?

I have one form for all languages and I want to sync all translations when user make changes. Lets say in the new edit French fields were removed/cleared so in this case sync should remove French entry instead of saving null/blank.

**Comment by Gummibeer** [comment]
Hey,

no - at the moment we don't have any sync method. The easiest way would be to delete all with locale not in post data.

```php
$post->translations()->whereNotIn('locale', $request->get('locales'))->delete();
```

And to save all post data you could use the overridden `fill()` method.

**Comment by buzzclue** [comment]
I have used [this ](https://docs.astrotomic.info/laravel-translatable/usage/forms) approach for form but in tabular format one for each language.

How do you handle:
```php
$request->get('locales')
```
in such form structure? 

Fill method doesnt work?
> And to save all post data you could use the overridden fill() method.
```php
$category->fill($request->all());
```

**Comment by Gummibeer** [comment]
So your form input names are in structure of `en[title]`/`locale[field]` or how are they structured?
If they are you can use `$request->all()` to `fill()` the category and to get all locales you can use:
```php
array_keys($request->all());
```

**Comment by buzzclue** [comment]
Yes that's the structure of my form fields
>en[title]/locale[field] 

Basically my main table also store some data i.e. show the category in main menu or status so the array_keys get me everythinig:

```php
array_keys($request->all());
array:8 [
  0 => "_method"
  1 => "_token"
  2 => "parent"
  3 => "order"
  4 => "status"
  5 => "show_menu"
  6 => "en"
  7 => "fr"
]
```

Also even if the data is blank the form will still appear in the request.

**Comment by Gummibeer** [comment]
Ok, in this case I would a more complex approach.

```php
collect($request->all())->filter(function($value, $key) {
  return is_array($value) && in_array($key, Locales::all());
})->keys()->all();
```

This should return all form keys which have an array as value - to don't use `id` column as Indonesian locale - and are part of the allowed locales.
It's not tested, but the idea should be clear.

**Comment by buzzclue** [comment]
Thanks for your help, i am grateful. Like i mentioned i am only **requiring** the default locale information all other languages are optional but gets posted.

So the sync is still a question, maybe i should delete all translations and save them all over and keep the current information in logs.

What about the fill method?

**Comment by Gummibeer** [comment]
This is no validation - so this is only how to get the posted locales. By inversing them `NOT IN` you can delete all unposted translations.

What's your question regarding the `fill()` method? Does it not work?

**Comment by buzzclue** [comment]
Fill method doesnt work?

```php
$category->fill($request->all());
```

**Comment by Gummibeer** [comment]
It does, why should it not? Do you get an error?

**Comment by buzzclue** [comment]
There is no error, it doesn't save information with 

```php
$category->save();
```

**Comment by Gummibeer** [comment]
Even if the test tests something else, the setup is the same 
https://github.com/Astrotomic/laravel-translatable/blob/3a490026e6efd4aaee2f95fc2252c4084d8ba17d/tests/TranslatableTest.php#L753-L788

So in general it works. Without any further details I can't help to find the problem.

**Comment by pjhartin** [comment]
@Gummibeer I think the expected behaviour that is being asked for here is something along these lines: (Where form is a translatable model, and title is a `$translatedAttribute`).

`
app()->setLocale('en');

$form = factory(Form::class)->create();
$form->title = 'Test';
$form->save();

$form->fill(['title' => 'new title']);
$form->save();
`

In this case, the use of `fill()` and `save()`, or update()`, does not seem to persist the title that was passed in the fillable array.

**Comment by Gummibeer** [comment]
@pjhartin they only have to be fillable in the translation model. 
If the attribute is fillable on the translation it doesn't use the translatable model logic.
https://github.com/Astrotomic/laravel-translatable/blob/889f8b91f28a8a72873099cf452945adbd03dc9f/src/Translatable/Translatable.php#L124-L134
