### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by FoLez** [Astrotomic/laravel-translatable#331]
Hello,

When this project will be compatible with Laravel 10 ?

Thanks

**Comment by ordago** [comment]
There is a PR for it:
#328 
You can subscribe to it.

**Comment by nekooee** [comment]
How much time is left until the version compatible with Laravel 10 is presented?

**Comment by Gummibeer** [comment]
https://github.com/Astrotomic/laravel-translatable/releases/tag/v11.12.0
