### ISSUE TITLE
Too many queries

### ISSUE THREAD

**Issue by Hossam-Tarek** [Astrotomic/laravel-translatable#336]
I'm using the translation in nearly all of my tables, and at the same time, I'm eager loading the translations for each model as follows

```php
class Provider extends Model implements TranslatableContract, HasMedia
{
    use Translatable;

    public function newQuery()
    {
        return parent::newQuery()->with(['translations']);
    }
}
```

The number of translation queries is huge and outweighs the number of queries to the original models.

![image](https://user-images.githubusercontent.com/23726675/223460642-065f6898-8a3c-4a2d-a51b-558ba588ab19.png)

Is there any solution to reduce the number of queries??

**Comment by Hossam-Tarek** [comment]
.

**Comment by Oleksandr-Moik** [comment]
Hmm... I could be wrong, but I think if you only need to get one translated model, I recommend using join query instead of eager download.

**Comment by cristiansoftlead** [comment]
No..I have many models.
