### ISSUE TITLE
How do I get only the "title" column, excluding the "content" column?

### ISSUE THREAD

**Issue by ast21** [Astrotomic/laravel-translatable#343]
Good afternoon! 

I have a table of `articles` and `article_translations`.
`article_translations` contains two translatable columns `title` and `content`. The `content` column can contain more than 10,000 characters. To get all the `articles` I do this:
```php
Article::withTranslation()->paginate(50);
```
and this code get all translated columns, including `content`, but the `content` column is not needed, and loads the request

How do I get only the `title` column, excluding the `content` column?

**Comment by ast21** [comment]
hello, any answers?

**Comment by omarcinkonis** [comment]
Hi, I found your question because I had a similar issue. To avoid loading unnecessary columns, you can add disableAutoloadTranslations() to the constructor of your model:

```
    public function __construct()
    {
        parent::__construct();

        self::disableAutoloadTranslations();
    }
```

If you want to disable autoload globally, you can change this translatable.php setting to false:
`'to_array_always_loads_translations' => false,`

**Comment by ast21** [comment]
Hi @omarcinkonis .

Thanks for your reply. Now I use that code:
```php
Article::query()
    ->with('translations', function ($query) {
        $query
            ->select(['article_id', 'locale', 'title']) // without 'content' because it's too big
            ->where('locale', app()->getLocale());
    })
    ->paginate();
```

After that, I wrap it in ArticleResource, there I already bring it to the form I need.
