### ISSUE TITLE
How to insert data in main post table ?

### ISSUE THREAD

**Issue by Abdulsami660** [Astrotomic/laravel-translatable#365]
hi , i have a main post table with column author and a post_translations table which holds title and content column. my question is how can i insert data in author field because documentation says pass $req->all() in create method of Post Model and your translations are inserted and post record as well but in my case author column is giving null and post_translation attribute are inserted 
![Screenshot (96)](https://github.com/Astrotomic/laravel-translatable/assets/92708691/ad216d0b-5db2-48b8-835c-d5e94e720056)
. please help.
Thanks

**Comment by OpJePl44tsm4n** [comment]
same here, i would expect the original create() function to still work the way it was intended... 
now it doesn't save because it's missing required fields. (the Query is stating no data is provided and all fields are empty)

**Comment by Abdulsami660** [comment]
My issue was solved . Because I didn't mass assign the model..

**Comment by minhkhoablieu** [comment]
> same here, i would expect the original create() function to still work the way it was intended... now it doesn't save because it's missing required fields. (the Query is stating no data is provided and all fields are empty)

same here. Have you solved this problem yet? Can you help me? 
Error
![image](https://github.com/Astrotomic/laravel-translatable/assets/12608657/db648f03-3134-41b5-89dc-03033d011c79)
Model
![image](https://github.com/Astrotomic/laravel-translatable/assets/12608657/0c2fe8ca-5fe7-4191-948f-219acc01707a)
Controller 
![image](https://github.com/Astrotomic/laravel-translatable/assets/12608657/7f6eeb36-e291-4e2b-ad6b-5d8d0e189f5e)
