### ISSUE TITLE
Add Laravel11 support

### ISSUE THREAD

**Issue by Gummibeer** [Astrotomic/laravel-translatable#385]
Laravel 11 will be released within a few weeks - so it should be added to composer.json & GitHub action test matrix & readme/docs.

**Comment by miladganjali** [comment]
Laravel 11 failed installation 

`  
Problem 1
    - astrotomic/laravel-translatable[v1.0.1, v2.0.0, v3.0.0, ..., v3.0.1, v4.0.0] require illuminate/support 4.0.* | 4.1.* -> found illuminate/support[v4.0.0, ..., v4.1.30] but these were not loaded, likely because it conflicts with another require.
    - astrotomic/laravel-translatable[v4.0.1, ..., v4.5] require illuminate/support ~4.0 -> found illuminate/support[v4.0.0, ..., v4.2.17] but these were not loaded, likely because it conflicts with another require.
    - astrotomic/laravel-translatable[v5.0, ..., v5.4] require illuminate/support ~5.0 -> found illuminate/support[v5.0.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - astrotomic/laravel-translatable[v5.5, ..., v5.6.1, v6.0, ..., v6.1] require illuminate/support ~5.1 -> found illuminate/support[v5.1.1, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - astrotomic/laravel-translatable[v7.0, ..., v7.3] require illuminate/support 5.4.* -> found illuminate/support[v5.4.0, ..., v5.4.36] but these were not loaded, likely because it conflicts with another require.
    - astrotomic/laravel-translatable[v8.0, ..., v8.1] require illuminate/support 5.5.* -> found illuminate/support[v5.5.0, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - astrotomic/laravel-translatable[v9.0, ..., v9.1.0] require illuminate/support 5.6.* -> found illuminate/support[v5.6.0, ..., v5.6.39] but these were not loaded, likely because it conflicts with another require.
    - astrotomic/laravel-translatable[v9.2.0, ..., v9.3.0] require illuminate/support 5.6.*|5.7.* -> found illuminate/support[v5.6.0, ..., v5.7.28] but these were not loaded, likely because it conflicts with another require.
    - astrotomic/laravel-translatable[v9.4.0, ..., v9.5.0, v10.0.0, v11.0.0] require illuminate/support 5.6.*|5.7.*|5.8.* -> found illuminate/support[v5.6.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - astrotomic/laravel-translatable[v11.1.0, ..., v11.3.0] require illuminate/contracts 5.6.*|5.7.*|5.8.* -> found illuminate/contracts[v5.6.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - astrotomic/laravel-translatable[v11.4.0, ..., v11.5.2] require illuminate/contracts 5.6.* || 5.7.* || 5.8.* || ^6.0 -> found illuminate/contracts[v5.6.0, ..., v5.8.36, v6.0.0, ..., v6.20.44] but these were not loaded, likely because it conflicts with another require.
    - astrotomic/laravel-translatable[v11.6.0, ..., 11.7.1] require illuminate/contracts 5.8.* || ^6.0 -> found illuminate/contracts[v5.8.0, ..., v5.8.36, v6.0.0, ..., v6.20.44] but these were not loaded, likely because it conflicts with another require.
    - astrotomic/laravel-translatable[v11.8.0, ..., v11.8.3] require illuminate/contracts 5.8.* || ^6.0 || ^7.0 -> found illuminate/contracts[v5.8.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - astrotomic/laravel-translatable[v11.9.0, ..., v11.9.1] require illuminate/contracts 5.8.* || ^6.0 || ^7.0 || ^8.0 -> found illuminate/contracts[v5.8.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - astrotomic/laravel-translatable[v11.10.0, ..., v11.11.0] require illuminate/contracts ^8.0 || ^9.0 -> found illuminate/contracts[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - astrotomic/laravel-translatable[v11.12.0, ..., v11.12.1] require illuminate/contracts ^8.0 || ^9.0 || ^10.0 -> found illuminate/contracts[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.3] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires astrotomic/laravel-translatable * -> satisfiable by astrotomic/laravel-translatable[v1.0.1, v2.0.0, v3.0.0, v3.0.1, v4.0.0, ..., v4.5, v5.0, ..., v5.6.1, v6.0, v6.0.1, v6.1, v7.0, ..., v7.3, v8.0, v8.1, v9.0, ..., v9.5.0, v10.0.0, v11.0.0, ..., v11.12.1].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require astrotomic/laravel-translatable:*" to figure out if any version is installable, or "composer require astrotomic/laravel-translatable:^2.1" if you know which you need.
`

**Comment by Gummibeer** [comment]
https://github.com/Astrotomic/laravel-translatable/releases/tag/v11.13.0
