### ISSUE TITLE
How to get all translations regardless of current locale?

### ISSUE THREAD

**Issue by megavolkan** [Astrotomic/laravel-translatable#39]
I'm building an admin panel and need to get all translated values (in 3 different languages) on the same page regardless of the current set locale.

An example of 
`{{$news->title}}`
works fine and displays value in current set locale as expected.

But i need to display values in all 3 languages on the same instance.

I tried something like below when current language is set to 'en':
`{{$news->translate('de')->title}}` //In order to get German translation

but it gives the error below:
`Trying to get property 'title' of non-object....`

How can i get the values in all languages?

**Comment by Gummibeer** [comment]
Hey,

first of all the `translate()` method returns the translation model or `null`. So if you get `of non-object` I would assume that it returned `null` which would mean that there is no `de` translation.
https://github.com/Astrotomic/laravel-translatable/blob/720eaeb2aeae937c6cfb400d5055f73c6f5588c6/src/Translatable/Translatable.php#L271-L274

To your original question: you could simply loop over `$model->translations` which is a normal has-many eloquent relationship.
https://github.com/Astrotomic/laravel-translatable/blob/720eaeb2aeae937c6cfb400d5055f73c6f5588c6/src/Translatable/Traits/Relationship.php#L78-L81

If you want to access the translations not in a loop and in a defined order you could use the `Locales::all()` or a hardcoded list and access `$model->translate(...)` but you will have to check if it's `null` or a model instance.

**Comment by megavolkan** [comment]
getTranslation() method is the one that works. Thanks.
