### ISSUE TITLE
Publishing to config directory for Laravel 11

### ISSUE THREAD

**Issue by Milosfamous** [Astrotomic/laravel-translatable#411]
**Issue description**
- This command doesn't work for Laravel version 11
**• php artisan vendor:publish ‐‐tag=translatable**

**How to solve this issue?**
- You should change above command to:
**• php artisan vendor:publish --provider "Astrotomic\Translatable\TranslatableServiceProvider"**

**Comment by Oleksandr-Moik** [comment]
Hi!

Where did you get this and what OS did you try it on?

It looks like your command has a broken dash symbol.
Your dash: `‐‐` - (`ord('‐') = 226`)
Dash copied from docs `--` (`ord('-') = 45`)

Publishing by tag still works well

**Comment by Milosfamous** [comment]
Hi,
In your package page on GitHub a found this link: [How to Add Multi-Language Models to Laravel QuickAdminPanel](https://quickadminpanel.com/blog/how-to-add-multi-language-models-to-laravel-quickadminpanel/)
In step 4 you can find how to publish config.php but in your package this artisan command not mentioned.
My Laravel 11 app runs on a VPS with Ubuntu 22.04 OS.

**Comment by Oleksandr-Moik** [comment]
Ok, I got it. Thank you.

Looks like just a typo in the article :)

Both publishing options are still valid - by tag and by provider. It does not need to be changed.

Even browser can find regular dash in this command ))
![image](https://github.com/Astrotomic/laravel-translatable/assets/50796878/396baf01-8575-49d6-bbe2-ed0f10e490a6)

**Comment by Milosfamous** [comment]
Thank you very much for your attention 🙏.

**Comment by Gummibeer** [comment]
Thanks for solving that one @Oleksandr-Moik ! 🙏
