### ISSUE TITLE
11.15 breaks codebase

### ISSUE THREAD

**Issue by tomvo** [Astrotomic/laravel-translatable#429]
**Describe the bug**
setDefaultLocale(): Return value must be of type Astrotomic\Translatable\Contracts\Translatable, App\Route returned

This happened when upgrading minor version to .15 and to be honest I don't think return type changes should be part of minor version jumps. 

**background**
I'm setting the default locale of a specific model in an observer based on a DB value so that an object is always returned in the language the user forces it in.

**Comment by Gummibeer** [comment]
So you return your model but your model does implement the interface?

**Comment by Oleksandr-Moik** [comment]
@Gummibeer, Yes, I can confirm. In my own experience, my colleagues and I don't always implement the interface in a model, we just a trait and that's enough for us.

Therefore, I suggest to use only phpdoc, at least for now.

Type added in [b46b3cc18140a54af3ecba7938f58569dcae86d6](https://github.com/Astrotomic/laravel-translatable/commit/b46b3cc18140a54af3ecba7938f58569dcae86d6#diff-6712c5a1b7b48f6157ed3188e5e922865c6594323295afb1efc2c1b0cdb14b23R308-R312)

**Comment by Gummibeer** [comment]
https://github.com/Astrotomic/laravel-translatable/commit/e6b3c13c89e9f9e851f5de2f87de8f7ddeb7bf8d

**Comment by Gummibeer** [comment]
https://github.com/Astrotomic/laravel-translatable/releases/tag/v11.15.1

**Comment by tomvo** [comment]
hey @Gummibeer sorry for my late reply and missing background info but I'm glad @Oleksandr-Moik added some more details as that was indeed the scenario.
