### ISSUE TITLE
Get translations of many rows returned by Eloquent

### ISSUE THREAD

**Issue by nickotodorov** [Astrotomic/laravel-translatable#44]
How to get translations for many rows retrieved by eloquent queries with one or few database queries? If there is no translation for some of these rows the default fallback to be used.
Example: SomeModel::all();
The problem is that I can translate one row at a time using the ->translate($locale) method but if you do that in php loop it will generate n+1 (where n is the number of rows to be translated) queries to the database which is not efficient.

**Comment by Gummibeer** [comment]
The easiest way would be to eager load the `translations` relationship. This will load all translations for all models in a single query.

**Comment by nickotodorov** [comment]
Could you please provide an example script with the simples possible model?

**Comment by Gummibeer** [comment]
```php
Post::with('translations')->get();
```

**Comment by evgenykhm** [comment]
how about create some scope for querying?
i create scope that cross join translate table fields, but if i want to access translatabe field it still generating many queries for it.
in some cases eager loading works slowly, than join query

**Comment by Gummibeer** [comment]
The package provides several scopes.
https://github.com/Astrotomic/laravel-translatable/blob/master/src/Translatable/Traits/Scopes.php

Including a `withTranslation()` scope which only loads the needed translation.

**Comment by evgenykhm** [comment]
Yes, and it's generate two query, but i want to do this in one join query.
I need the ability to ignore recieving translations fields when they are already recieving by query, or something like this.

**Comment by Gummibeer** [comment]
It's not possible to have the translated fields in the attributes of the main model without any adjustments. You would have to adjust the getter and setter method.

Because joining removes all benefits of this package (model instance, type casts, attribute getter/setter) it's also not on the current roadmap.
