### ISSUE TITLE
Searching in translation tables

### ISSUE THREAD

**Issue by gyan111** [Astrotomic/laravel-translatable#45]
I am creating search field.

Is there any simple way to search from translation tables.
Will the search be efficient than keeping data in same table if I have only two languages?

**Comment by Gummibeer** [comment]
The package provides several scopes to search translations.
https://docs.astrotomic.info/laravel-translatable/package/scopes#where-translation

The performance depends on a lot of factors. How large your main table is, how many records in both of them, your indexes, the type and size of the translated values and so on.
So I can't tell you. At all a relational database like MySQL isn't made for fulltext search. If you need fast and powerful search you should check out Laravel scout.

**Comment by gyan111** [comment]
Thanks
