### ISSUE TITLE
Laravel 6.0 compatibility

### ISSUE THREAD

**Issue by vegazrelli** [Astrotomic/laravel-translatable#51]
Laravel 6.0 LTS is almost out, when can we use the package with the new version?
Thanks

**Comment by Gummibeer** [comment]
Hey, I've added a branch to test with the current dev version. Like expected everything looks fine and the package is ready to go with it.
Will do my best to release it as fast as possible after official L6 release.

https://github.com/Astrotomic/laravel-translatable/pull/52
