### ISSUE TITLE
how to display the translated text with current locale

### ISSUE THREAD

**Issue by ikkosatrio** [Astrotomic/laravel-translatable#55]
i already set the locale. and check with app()->getLocale() . but when i call $object->title it only show the default locale

**Comment by Gummibeer** [comment]
Have you set a locale in the translatable config?
If so this overrides all locales. To test which locale is used by the package you should use `Locales::current()`.

**Comment by ikkosatrio** [comment]
when i try "Locales::current()" is not found class, what class i should use/load?

**Comment by Gummibeer** [comment]
this one:
https://github.com/Astrotomic/laravel-translatable/blob/master/src/Translatable/Locales.php
https://docs.astrotomic.info/laravel-translatable/package/locales-helper

**Comment by ikkosatrio** [comment]
![image](https://user-images.githubusercontent.com/17069028/63946371-3a67c200-ca9f-11e9-862d-a854b11fa0e8.png)
i got this error

**Comment by ikkosatrio** [comment]
![image](https://user-images.githubusercontent.com/17069028/63946392-46538400-ca9f-11e9-9ece-66b897fb64c2.png)
also i run this code but i doesn't work too

**Comment by ikkosatrio** [comment]
oh i know, i typo hehe. it supposed to be "app('config')->set('translatable.locale', $lang);" without "s". thx it work

**Comment by Gummibeer** [comment]
The `Locales` helper class is a bound service https://github.com/Astrotomic/laravel-translatable/blob/c7d3eefe7bd8390fa325b555583a127134c7ce9b/src/Translatable/TranslatableServiceProvider.php#L33-L37

**Comment by ikkosatrio** [comment]
how to get  data with "where" which is the column is translatable? exp : 
![image](https://user-images.githubusercontent.com/17069028/64353822-9646c380-d028-11e9-8dab-96c94be38bb6.png). slug is translatable column

**Comment by Gummibeer** [comment]
https://docs.astrotomic.info/laravel-translatable/package/scopes#where-translation

**Comment by arturmamedov** [comment]
So i need set the config on the fly `config(['translatable.locale' => $lang]);` the documentation say that Astrotomic get the Laravel default locale (that i set in one of the middlewares `app()->setLocale($lang);`), so its no working like expected ...

**Comment by Gummibeer** [comment]
@arturmamedov it loads the app locale as long as no translatable locale is configured.
https://github.com/Astrotomic/laravel-translatable/blob/b6bbb29c5677e94695f373eda0c71d4e46bdfdf0/src/Translatable/Locales.php#L46-L49
