### ISSUE TITLE
Error on Fresh Installation

### ISSUE THREAD

**Issue by gyan111** [Astrotomic/laravel-translatable#61]
Laravel 6
**Issue 1:**
Class App\Author contains 18 abstract methods and must therefore be declared abstract or implement the remaining methods.

I have checked and this issue is occurring when I add "implements TranslatableContract" to the class

**Issue 2:** (Solved)
If I add
`$table->foreign('post_id')->references('id')->on('posts')->onDelete('cascade');`
I am getting an error while migrating

> SQLSTATE[HY000]: General error: 1005 Can't create table `ts`.`post_translations` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `post_translations` add constraint `post_translations_post_id_foreign` foreign key (`post_id`) references `posts` (`id`) on delete cascade)

**Comment by gyan111** [comment]
If someone facing the issue as I have mentioned on issue 2: 
You need to change the key from unsignedInteger to unsignedBigInteger.
check 
[](https://stackoverflow.com/questions/32669880/laravel-migration-foreign-key-constraint-is-incorrectly-formed)

**Comment by Gummibeer** [comment]
Your issue 2 depends on your primary key type. It could also be string for UUIDs or whatever you choose.

Issue 1 is solvable by also adding the trait like stated in the docs. The interface is for custom implementations.
https://docs.astrotomic.info/laravel-translatable/installation
https://github.com/Astrotomic/laravel-translatable/blob/master/src/Translatable/Translatable.php
