### ISSUE TITLE
Remove need to specify the language when updating Eloquent object

### ISSUE THREAD

**Issue by egbertwietses** [Astrotomic/laravel-translatable#62]
Let's say we have a product that has some translatable attributes for example name.
Would be nice if you could just do this.

$product = $product->update(request()->all());
or
$post->title = 'My cool post'; // uses default locale.
$post->save();

And it will update using default locale. Now you have to specify when updating:

current:
$post->translate('en')->title = 'My cool post';
$post->save();

**Comment by Gummibeer** [comment]
This is already possible. Only the docs could get improved. Do you want to do it?

https://github.com/Astrotomic/laravel-translatable/blob/078a22ea96582f7f518f5418ee7e57e3746fb032/src/Translatable/Translatable.php#L270
https://github.com/Astrotomic/laravel-translatable/blob/078a22ea96582f7f518f5418ee7e57e3746fb032/src/Translatable/Translatable.php#L352-L359

**Comment by egbertwietses** [comment]
Thnx for your fast reply!, with some more research I found out why it in our case didn't work in one of our tests. Found out that our default configuration of translatable was wrong.

**Comment by Lloople** [comment]
I'm working on a PR regarding this topic, and I have a question about the `fill` method found in the docs. Will it also work with the `$request->all()` method?

```php
$post->fill([
  'en' => [
    'title' => $request->input('en.title'),
  ],
  'de' => [
    'title' => $request->input('de.title'),
  ],
]);
$post->save();
```

Will be the same as

```php
$post->fill($request->all());
$post->save();
```

Which is also the same as 

```php
$post->update($request->all());
```

Since the inputs are 

```html
<input type="text" name="en[title]" />
<input type="text" name="de[title]" />
```

Or I'm missing something?

**Comment by Gummibeer** [comment]
@Lloople everything right. The logic is placed in `setAttribute()` which is the lowest method and called from everywhere.

**Comment by egbertwietses** [comment]
@Lloople thnx for adding the doc. 👍
