### ISSUE TITLE
Saving translated locale attributes

### ISSUE THREAD

**Issue by Thuongkim** [Astrotomic/laravel-translatable#64]
I try to save: `$slider = Slider::create($input);` with $input:
```
array:6 [▼
  "_token" => "6EReMQzWYsPg8Snwc2dfcvsvj1Yn08cTw51dFiWi"
  "title" => "we"
  "content" => "asd"
  "status" => "1"
  "locale" => "vi"
  "image" => "/images/slider/slide-5826879d561ba54aa8e7a788569832e85486308b.png"
]
```
but it save default locale(en). How i can solve it? Thank you!
Here's my database:
![image](https://user-images.githubusercontent.com/41858767/65481528-de3a6700-debf-11e9-8ddc-223a37792204.png)

**Comment by Gummibeer** [comment]
You have multiple options. Have you checked the [form docs](https://docs.astrotomic.info/laravel-translatable/usage/forms)?

I would move the locale in input name. But you can also use the `setDefaultLocale()` method - `new Slider; $slider->setDefaultLocale(); $slider->fill();`. Or set the app locale before creating.

**Comment by Thuongkim** [comment]
It works, when i use `setDefaultLocale('fr')`. But when i use another locale like: `vi,ru...`  it doesn't  work. So what's locale this package support? Anyway, Thank you for saving my day!

**Comment by Gummibeer** [comment]
It's up to you which locales are supported.
https://docs.astrotomic.info/laravel-translatable/installation#configuration
https://docs.astrotomic.info/laravel-translatable/package/locales-helper
