### ISSUE TITLE
Field with null value gets data from other language field.

### ISSUE THREAD

**Issue by notflip** [Astrotomic/laravel-translatable#65]
I have a **NewsItems** table as follows

![Screenshot 2019-09-24 at 14 31 45](https://user-images.githubusercontent.com/4146384/65511705-0f269600-ded8-11e9-94eb-080aa32d7164.png)

The issue here is that when I go to the show method of the NewsItem on the 'en' website, it's showing me the body content of the 'nl' row.
Once I add some data in the 'en' row's body, it's fine,

**but when it's set to null, it's showing data from another translation**
Is there any way to fix this?

**Comment by Gummibeer** [comment]
You can disable or customize the fallback logic: https://docs.astrotomic.info/laravel-translatable/package/fallback-locale
You can even customize when a translatable attribute is detected as empty: https://docs.astrotomic.info/laravel-translatable/package/fallback-locale#customize-empty-translation-property-detection
By default it's a simple `empty()` check. https://github.com/Astrotomic/laravel-translatable/blob/f7e595be5a05aa8ff47cdfda2d531c4b9a4a912f/src/Translatable/Translatable.php#L308-L311
