### ISSUE TITLE
Create data issue

### ISSUE THREAD

**Issue by cvhainb** [Astrotomic/laravel-translatable#66]
Hello,

This is my submit data: 
![1](https://user-images.githubusercontent.com/6187884/65612232-381c5900-dfb4-11e9-8074-0614710adeb6.png)

Missed "de" language:
![2](https://user-images.githubusercontent.com/6187884/65612259-44081b00-dfb4-11e9-815e-128728855a88.png)

**Comment by Gummibeer** [comment]
Hey,

have you followed the installation procedure? Especially the [configuration](https://docs.astrotomic.info/laravel-translatable/installation#configuration) part?
The most common reason that a locale isn't saved is that it's not configured as a locale.

**Comment by cvhainb** [comment]
> Hey,
> 
> have you followed the installation procedure? Especially the [configuration](https://docs.astrotomic.info/laravel-translatable/installation#configuration) part?
> The most common reason that a locale isn't saved is that it's not configured as a locale.

Thank you so much!
