### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by cvhainb** [Astrotomic/laravel-translatable#69]
Hello,

I'm a newbie inLaravel. I have tried to create a form request and add this in rules(): 

```
return $rules = [
    'translations.%name%' => 'required|string',
];

```
however it did not work. 

This is my array: 

```
translation.en.name
translation.de.name
translation.fr.name
```
So, my question is how to validate with this? 

Thank you.

**Comment by Gummibeer** [comment]
Hey,

you have to wrap your `$rules` array in the `RuleFactory::make($rules);`. This will replace your placeholder with all locale field combinations you have configured.

For further details please check the docs:
https://docs.astrotomic.info/laravel-translatable/package/validation-rule-factory

**Comment by cvhainb** [comment]
Dear Gummibeer,

Thank you for replied. Yes, I have read it some times and try to learn more about laravel validation but it's not lucky for me. I'm a newbie. Is there example about this? If you have one, please send me the URL.

**Comment by Gummibeer** [comment]
Instead of your current
```php
return $rules = [
    'translations.%name%' => 'required|string',
];
```
you just do
```php
return RuleFactory::make([
    'translations.%name%' => 'required|string',
]);
```
It will still return an array but will parse it and replace the placeholders.

**Comment by cvhainb** [comment]
You're awesome! thank you so much.

**Comment by Gummibeer** [comment]
Thanks! :)
Is there anything we could improve in the docs? Writing docs as the maintainer is every time hard because I don't now which could be unknown or has to explained better with an example.

**Comment by cvhainb** [comment]
I think it's better if you have a few example how to do that because it's more easier for newbie, like me.

I have fixed the problem. Thank you so much ^^!

**Comment by turkidkil** [comment]
This is true?

< input name="translations[en][name]" > ?
Because Validation Rule did not work for me!


 ```
       $rules = [
            'translations.%name%' => ['required_without:translations.%name%', 'nullable', 'min:3', 'max:50'],
        ];

        RuleFactory::make($rules);
        $request->validate($rules);
....
```
