### ISSUE TITLE
Delete the translations by default

### ISSUE THREAD

**Issue by Lloople** [Astrotomic/laravel-translatable#85]
In my opinion, since a translation record is useless without a **Translatable** model related to it, it should be deleted by default by the package using some kind of technique like an event listener on the `delete` event.

Right now this logic is provided by Database engine `on delete cascade` feature or equivalent, so it will not work by default with Laravel's soft deletes.

This automatic deletion feature could also be turn off by adding a property to the package configuration file or in a specific model.

Without this feature, the user have to override the `delete` method in the model like this

```
public function delete()
{
  $this->translations()->delete();
  $this->translations->each->delete(); // or like this if you have soft-deletes and want to keep the records
  return parent::delete();
}
```

This is a really huge breaking change, maybe the package could have this feature turned off by default for a few versions 🤔

**Comment by Lloople** [comment]
I'll be glad to take a look into this. Maybe next week if I can find some free time

**Comment by Gummibeer** [comment]
Is now part of #75 / #76 to prevent conflicts in the testsuite.
