### ISSUE TITLE
Create models in seeders

### ISSUE THREAD

**Issue by jordantsap** [Astrotomic/laravel-translatable#90]
In the docs and in Sep tutorial the translations are saved using new () and save ()
What about create ()??
I use Company::create ($attributes) but it saved only the default locale

**Comment by Lloople** [comment]
Hi @jordantsap, you can use the `create` method with both the array syntax and the plain syntax:

```
Animal::create([
  'en' => [
    'name' => 'Bear'
  ],
  'es' => [
    'name' => 'Oso'
  ]
]);
```


```
Animal::create([
  'name:en' => 'Bear',
  'name:es' => 'Oso'
]);
```

**Comment by jordantsap** [comment]
I can now understand my mistake.
I currently use app ()->setLocale ('es'); outside each create seeders,
I should use inside each create function or using your implementation.
Thanks again
